### ISSUE TITLE
Docs: Behaviors "look up" page for learning about keymaps

### ISSUE THREAD

**Issue by petejohanson** [zmkfirmware/zmk#1044]
Currrently, if users are viewing a sample keymap file, and trying to understand all the behaviors they see there, they need to dig into our individual behavior docs to find each one.

It would be nice to have an aggregated index/lookup page, at the top of the "Behaviors" nested sidebar section, that gives has a table from "sample behavior" to the docs describing that behavior.

**Comment by caksoylar** [comment]
Related: #525

**Comment by adityarawat1223** [comment]
can I work on this? if yes can someone guide me on how should I proceed?

**Comment by caksoylar** [comment]
You most certainly can, although it helps to be familiar with ZMK behaviors and the documentation structure. Pete's initial idea still sounds useful to me:

> It would be nice to have an aggregated index/lookup page, at the top of the "Behaviors" nested sidebar section, that gives has a table from "sample behavior" to the docs describing that behavior.

So you'd want to add a page like `docs/docs/behaviors/index.md`, add a link to it in `docs/sidebars.js`, then fill it in. Its contents can could be a table or markdown list of mappings from pre-defined behavior labels to links to the corresponding behavior docs page.
E.g.
```
- `&kp`: [Key press behavior](key-press.md)
- ...
```

It would of course be nice to have some preamble explaining the purpose of the page and give a bit of context.

**Comment by petejohanson** [comment]
Yeah, that's exactly the high level jist of it. I don't know if the text description should be a bit longer for each one, or if we might add a small summary of the behavior, e.g.:

```
`&kp`: [Key Press Behavior](key-press.md) - Send HID keycodes to the connected host
```

**Comment by huber-th** [comment]
This would be a very nice to have. @adityarawat1223 are you working on this? If not, I could take this one on.

Before I go through the whole list of behaviors, is this kind of what you had in mind @petejohanson ?

<img width="1166" alt="Screenshot 2024-03-04 at 22 58 08" src="https://github.com/zmkfirmware/zmk/assets/113915837/4d27b4e8-0ffa-4146-acf5-6cfcb5047d9e">

**Comment by petejohanson** [comment]
> This would be a very nice to have. @adityarawat1223 are you working on this? If not, I could take this one on.
> 
> Before I go through the whole list of behaviors, is this kind of what you had in mind @petejohanson ?
> 
> <img width="1166" alt="Screenshot 2024-03-04 at 22 58 08" src="https://github.com/zmkfirmware/zmk/assets/113915837/4d27b4e8-0ffa-4146-acf5-6cfcb5047d9e">
> 

Exactly right! I'm not sure if it's useful to break the table into a few high level categories or not, if it ends up too long. I also had considered an "Examples" column showing how it looks to use it.

**Comment by huber-th** [comment]
Great! I agree that it probably would make sense to identify some high level categories and break it up a bit to avoid a large single table. 

I'll see what might make sense to break it up and work on a proposal we can iterate on.
