### ISSUE TITLE
initial user config fails during west_update fatfs, hal_quicklogic

### ISSUE THREAD

**Issue by chrismelba** [zmkfirmware/zmk#1075]
I get a lot of tags created but an error on 

ERROR: update failed for projects: fatfs, hal_quicklogic

Trying to create redox map with nice!nano2
Used powershell on windows to initialize repo
All defaults used

run hopefully visible at
https://github.com/chrismelba/zmk-config/runs/4640998490?check_suite_focus=true

**Comment by caksoylar** [comment]
I couldn't see anything abnormal with your config repo. The error looks like it could be transient, can you try triggering the workflow again?

**Comment by chrismelba** [comment]
Yup, seems to have gone away. Blame US_EAST_1 again?
