### ISSUE TITLE
RGB don't start off

### ISSUE THREAD

**Issue by OsiNubis99** [zmkfirmware/zmk#1091]
I put 
`CONFIG_ZMK_RGB_UNDERGLOW_ON_START=no`
in the .config file but when the keyboard is turn on the RGB is ON...
The only way that i can start without RGB is disable all RGB settings.

**Comment by rbitanga** [comment]
Zephyr and thus ZMK use the Linux kernel's KConfig syntax where boolean values are `y` or `n` and not `yes` or `no`. If you are setting it to `n` and it isn't working, then your RGB underglow state was probably persisted by the Zephyr settings subsystem. Your config setting is essentially ignored as the underglow state is overwritten by the persisted settings via `settings_load_subtree("rgb/underglow");`.

You'll need to add `#include <dt-bindings/zmk/rgb.h>` to your keymap and have a key bound to `&rgb_ug RGB_OFF` or `&rgb_ug RGB_TOG` which you can then press to persist the off state

**Comment by OsiNubis99** [comment]
Please review my zmk-config bc I do everything u say and I still have the RGB problem. Only the "primary"(left) half get the RGB On or Off but the other half didn't change the initial settings

**Comment by OsiNubis99** [comment]
I made a hard reset to my two n!n2 and all problems with the initial state is solved.

But I still have a RGB problem with the "slave"(right) half, I can't turn ON or OFF this half. It keeps the initial state. So if I use the RGB_tg button that only affects the "primary"(left) half. Do u have any recommendations?

**Comment by caksoylar** [comment]
Did you try rebuilding your firmware after #547 was merged end of January? The `RGB_TOG` and similar behaviors should now apply to both halves.
