### ISSUE TITLE
[Question] Weird behaviour with the last row

### ISSUE THREAD

**Issue by wizar** [zmkfirmware/zmk#1093]
- MCU: nrfmicro_13
- Board: jorne

I noticed quite weird behaviour - after flashing ZMK firmware into nrfmicro the last raw (4) doesn't work at all. Surprisingly enough, after flashing it with [test firmware](https://github.com/joric/qmk/blob/nrf52-jorne/keyboards/jorne_ble/slave/blink.c) and reflashing with ZMK this problem goes away.

I guess there is nothing to fix, and I doubt this issue is caused by ZMK itself, but I'm curious if somebody have any thoughts on why this is happening

**Comment by caksoylar** [comment]
Hi, I think this sort of discussion is more appropriate for the [ZMK Discord](https://zmk.dev/community/discord/invite). It helps to keep Github issues specific and geared towards known issues and feature requests.
