### ISSUE TITLE
Powershell setup script command closes terminal window

### ISSUE THREAD

**Issue by joelspadin** [zmkfirmware/zmk#1206]
The command on https://zmk.dev/docs/user-setup for running the setup script from PowerShell runs the commands in the current interpreter's context, so any return statements in the setup script for bailing on error just close the entire terminal window.

One solution that was suggested on Discord is to change the command to wrap everything in another instance of PowerShell:

```ps
powershell -Command "iex ((New-Object System.Net.WebClient).DownloadString('https://zmk.dev/setup.ps1'))"
```

**Comment by caksoylar** [comment]
See #1128 for a PR.
