### ISSUE TITLE
Configured device name is not displayed on macOS

### ISSUE THREAD

**Issue by tominabox1** [zmkfirmware/zmk#124]
Tested on both Catalina 10.15.6 and Big Sur Public Beta 5. 

Device connects but is not advertised as a keyboard (icon does not indicate keyboard) and is only shown as a MAC address. 

When connected, it works and behaves fine, so this appears to be a minor graphical issue.

Bluetooth Preference Pane:
![image](https://user-images.githubusercontent.com/14228518/90990647-a53fc200-e568-11ea-92c0-bf8dd01148e4.png)

System Information bluetooth: 
![image](https://user-images.githubusercontent.com/14228518/90990663-c6a0ae00-e568-11ea-9304-efb63406d967.png)

**Comment by luantty2** [comment]
I have the same issue

**Comment by Na-Cly** [comment]
Can confirm and device was having issues pairing. iPhone had no issue with display name or connection.

**Comment by bendalton** [comment]
Same experience here

**Comment by a826889260** [comment]
The media key cannot be used on the iPad
