### ISSUE TITLE
Rolling shifted -> unshifted keycode (of the same basic key) does not send unshifted keycode.

### ISSUE THREAD

**Issue by elagil** [zmkfirmware/zmk#1262]
I have the keycode for `+` on a key of its own. When I try to roll the key combination `+` -> `=`, the `=` is not sent. I want to stress that `+` and `=` are just `LS(=)` and `=`, so the same basic key.

Rolling from a shifted keycode to a regular keycode works, if it is not the same key, e.g.  `+` -> `a`.

Pressing `a` immediately cancels the modifier and sends `a`.

Might be related to 7b7701ae90469b920cd78e2ab7aca0c470140b7a?

**Comment by kurtis-lew** [comment]
Are the problems occurring here possibly the same as those in #1076?

**Comment by elagil** [comment]
Yes, I didn't see that issue. Thanks for pointing me to it. Closing, as this is a duplicate.
