### ISSUE TITLE
Documentation Improvement: How to reduce build time

### ISSUE THREAD

**Issue by infused-kim** [zmkfirmware/zmk#1285]
This is regarding this page:
https://zmk.dev/docs/development/build-flash

If you follow the instructions there, west build re-compiles most code (even if it hasn't been changed) on each build leading to a very long build time.

But you can dramatically reduce it by doing an initial build with all the extra parameters like:
```
west build -d build/sofle/left -b nice_nano_v2 -- -DSHIELD=sofle_left -DZMK_CONFIG="/workspaces/zmk-config/config"
```

And then future builds with just:
```
west build -d build/sofle/left
```

The additional settings are cached in the directory.

On my system a pristine build takes exactly 3min, a non pristine build with all the parameters above takes 2min 20seconds and a build with just the `-d` parameter takes just 1m 20seconds (a 44% reduction from the non pristine build!).

This really adds up when developing and testing frequently.

You can check out out this conversation in development for more details:
https://discord.com/channels/719497620560543766/719544230497878116/971091356791476284

I think this would be a worthy addition to the documentation.

**Comment by dxmh** [comment]
Addressed with https://github.com/zmkfirmware/zmk/pull/1324.
