### ISSUE TITLE
Copying .UF2 on nice!nano doesn't seem to work

### ISSUE THREAD

**Issue by jwav** [zmkfirmware/zmk#1307]
I use Ubuntu 21.10.
My nice!nano seems to work, it was outputting text before today's fiddling session.
I generated a zmk.uf2 with no error and have tried to copy it on a nice!nano with the following variations:

- drag & drop zmk.uf2 as is
- same thing with the `cp` command
- rename to "CURRENT.UF2" before drag & drop
- same thing with the `cp` command

In all cases, the following happens:

- The nice!nano reboots (normal)
- Once connected, if I press any key, nothing happens
- When running a diff between the currently on-board "CURRENT.UF2" and the generated "zmk.uf2", it returns: `Binary files zmk.uf2 and CURRENT.UF2 differ`

I may be wrong but it seems to mean the nice!nano wasn't flashed. Any idea on how to solve this ?

**Comment by joelspadin** [comment]
The UF2 bootloader isn't a real file system, so it doesn't matter what the file you copy is named. IIRC, the CURRENT.UF2 file includes other things such as the bootloader itself, so it will not match the ZMK firmware file.

https://zmk.dev/docs/development/usb-logging/ might help with figuring out why the keyboard isn't outputting anything.

**Comment by jwav** [comment]
Thanks for the info, I was kind of expecting for the uf2 `diff` to be meaningless.
I've successfully logged into the nice!nano's tty console with `tio` thanks to your link, but I can't figure out what to do with it. I've typed on the keeb equiped with the nice!nano, but it doesn't output anything.

What do you suggest I do now?

**Comment by joelspadin** [comment]
Does it output anything at all when you connect? If not, logging might not be set up properly. If so, but it's just not logging anything when you press a key, either the firmware or the hardware isn't working. You could try to narrow it down by using something like tweezers to bridge a row pin and column pin (check the schematic or ZMK shield definition for your keyboard) to eliminate the PCB and switches as problems.

**Comment by jwav** [comment]
Currently, no output is generated at any time, in the serial console or elsewhere.

I set up logging according to the official ZMK link you provided (https://zmk.dev/docs/development/usb-logging/).
If I missed anything, it's not listed in there; but I don't think that's the problem.

It's not the PCB either. I've used this keyboard for a while with an Elite-C and also a previous firmware on that very same nice!nano, which was at that time working as a wired keyboard and outputting correct letters.
Which also suggests that the nice!nano is not at fault either although I'll try a new one in the future.

BTW it's a Corne, but I don't think that's relevant.

**Comment by codeanpeace** [comment]
Running into something similar here – first flash of default keymap went fine, but after customizing the keymap and updating the configuration file, it builds just find via Github actions but reflashing using the new UF2 files results in no changes to the physical keymapping. Any idea what might be going on?

**Comment by caksoylar** [comment]
@codeanpeace Looks like you are running into issue #1144 if you are working with https://github.com/codeanpeace/zmk-config. #1306 will fix it, but meanwhile you can rename your keymap and conf files to `kyria.keymap` and `kyria.conf` to get them picked up by the build.

**Comment by codeanpeace** [comment]
Thanks @caksoylar  – impressed by the quick response! I managed to figure it out and saw your helpful comment moments after I pushed the file rename changes.

**Comment by jwav** [comment]
@caksoylar > Good pointers, mate. Any idea on what I might try on my end?

**Comment by codeanpeace** [comment]
> a previous firmware on that very same nice!nano, which was at that time working as a wired keyboard and outputting correct letters

Total shot in the dark, but maybe it has something to do with [Output Selection](https://zmk.dev/docs/behaviors/outputs)?

**Comment by jwav** [comment]
@codeanpeace > Fair guess. I'll try to check this out today.

**Comment by billyjacoby** [comment]
Just wanted to chime in here, I'm having the same issue. 

I'm on macOS & when i copy the UF2 file, i get the "DIsk not ejected properly" message and the device can't be found until I click reset twice.

I deleted the Current.UF2 and see it replaced when I copy the new file so I assume something is happening

**Comment by petejohanson** [comment]
> Just wanted to chime in here, I'm having the same issue. 
> 
> I'm on macOS & when i copy the UF2 file, i get the "DIsk not ejected properly" message and the device can't be found until I click reset twice.
> 
> I deleted the Current.UF2 and see it replaced when I copy the new file so I assume something is happening
> 
> To add to this it looks like the left half will flash and work just fine, but the right half does not

From discord, I see this was some confusion about split peripheral behavior.

**Comment by edwin-koh** [comment]
> > Just wanted to chime in here, I'm having the same issue.
> > I'm on macOS & when i copy the UF2 file, i get the "DIsk not ejected properly" message and the device can't be found until I click reset twice.
> > I deleted the Current.UF2 and see it replaced when I copy the new file so I assume something is happening
> > To add to this it looks like the left half will flash and work just fine, but the right half does not
> 
> From discord, I see this was some confusion about split peripheral behavior.

@petejohanson Have you found the solution for this? I have exactly the same issue.

**Comment by auryn31** [comment]
same here, is there an update?

**Comment by caksoylar** [comment]
There is no currently known issue about flashing failing, closing this. Above quoted symptom is documented in https://zmk.dev/docs/troubleshooting#file-transfer-error and is not a flashing issue.

**Comment by auryn31** [comment]
> There is no currently known issue about flashing failing, closing this. Above quoted symptom is documented in https://zmk.dev/docs/troubleshooting#file-transfer-error and is not a flashing issue.

Thank you, found this as well :) 
And was on my side. But thank you for the comment!!
