### ISSUE TITLE
&rgb_ug RGB_COLOR_HSB on split keyboard is not global when used within macro

### ISSUE THREAD

**Issue by ivandaho** [zmkfirmware/zmk#1347]
When using using the example code as seen in https://zmk.dev/docs/behaviors/macros#layer-activation--more for **Layer + Underglow Color**, underglow color is only set for the central side of the keyboard during macro execution

- Color for peripheral side is unaffected by the macro
- If i change underglow color directly with `&rgb_ug RGB_COLOR_HSB(86,81,85)` outside of a macro, it changes for both sides as expected

Tested on `main` branch, built via docker method for Corne/NRFMicro
Unsure if any other `&rgb_ug` behavior is affected

reproducable in https://github.com/ivandaho/zmk/tree/corne-ivan, in case you have a corne/NRFMicro
- run `./buildcorne.sh` in `app` directory
- flash firmware
- turn on LEDs by holding these buttons on the central/left side down in this order
  - leftmost button on bottom row
  - rightmost button on bottom row
  - "D" key (4th button on 2nd row)
- press either:
  - leftmost button on bottom row (central/left side)
  - middle button on bottom row (peripheral/right side)

**Comment by tokazio** [comment]
Same issue here https://github.com/tokazio/zmk-config-sofle

**Comment by caksoylar** [comment]
Most likely related to #1494

**Comment by caksoylar** [comment]
@aDogCalledSpot You can test #2409 which should fix this issue.

**Comment by caksoylar** [comment]
This should be fixed by #2409, please report if there's an issue.
