### ISSUE TITLE
When `ZMK_BACKLIGHT_AUTO_OFF_USB=y`, disable backlight at start if no USB.

### ISSUE THREAD

**Issue by petejohanson** [zmkfirmware/zmk#1361]
If the a single color backlight config setting `ZMK_BACKLIGHT_AUTO_OFF_USB=y`, and we start ZMK from battery, currently the backlight is initialized on, and doesn't turn off, even though USB isn't present. Came up when testing the equivalent behavior for RGB Underglow in #1010 

Need to change the backlight init code to default the state based on the USB state in `app/src/backlight.c`.

**Comment by caksoylar** [comment]
This is fixed by #1362 right?

**Comment by petejohanson** [comment]
Should be, yes. Closing, but feel free to re-open if needed.
