### ISSUE TITLE
Sticky layer not released with sticky key and key with modifier

### ISSUE THREAD

**Issue by xudongzheng** [zmkfirmware/zmk#1365]
To reproduce:

1. Press and immediately release `&sk LSFT` on layer 0 with `quick-release` enabled for `&sk`.
2. Press and immediately release `&sl 2` to go to layer 2.
3. Press and immediately release `&kp RA(N)` on layer 2 twice - it appears that keymap does not revert to layer 0 after the first press though it does revert after the second press.

A few observations:

- This issue does not occur if `&kp LSFT` is used instead of `&sk LSFT`.
- This issue does not occur if `&kp N` is used instead of `&kp RA(N)`.
- This issue does not occur if `&sk LSFT` is held throughout 2 and 3.
- This issue does not occur without `quick-release` for `&sk`.

This combination is useful for languages such as Spanish where you can have `&kp RA(N)` defined for ñ and use it in conjunction with `&sk LSFT` to get Ñ.

**Comment by jkozdon** [comment]
I am seeing similar issues to this as well with `&sk LSFT` and `&sl 2`.
