### ISSUE TITLE
Issue waking from sleep on OS X

### ISSUE THREAD

**Issue by vaheder** [zmkfirmware/zmk#1372]
I've recently started having an issue where my keyboard will not send keys after the computer wakes from sleep. [This is my config repo](https://github.com/vaheder/zmk-config), where you can have a look at the Actions for the build versions and configurations I've been using for the last few tests. I've also included the logs in an attachment to this ticket in which the keyboard is complaining about not having an active address for the current profile when keys are pressed. The logging starts after the computer wakes from sleep, then a couple keys are pressed. [This is the build Action for the logging attached.](https://github.com/vaheder/zmk-config/actions/runs/2606245154) If I reset the left side controller via the board's reset button, it's able to communicate correctly again.

Some details about the environment:
Mac Mini, OS X 12.4
Levinson/Let's Split, wired via USB-C, not currently using bluetooth to communicate with the computer
pair of nice!nano v2s

Please let me know what further information or testing I can provide.

Logging:
[20220703_zmk_wake.txt](https://github.com/zmkfirmware/zmk/files/9035456/20220703_zmk_wake.txt)

**Comment by vaheder** [comment]
Quick update: after a week of testing [this version of ZMK](https://github.com/vaheder/zmk-config/pull/4), I've not experienced the same issue after waking from sleep.

**Comment by dpangier** [comment]
Having the same issue on latest main, with nice!nano and the cradio shields over USB.

**Comment by co-dan** [comment]
Similar issue with the latest version of ZMK using nice!nano

**Comment by droghio** [comment]
I experienced a similar issue on Windows 10l. I would put the computer to sleep, wait about a second, press a key on the keyboard. Incidentally the keyboard press would wake the computer but no further input would be recognized. Resetting the MCU, un-plugging  and re-plugging USB, or issuing the `&reset` behavior would fix the functionality.

Based on a discussion with honorless & bravekarma from the Discord I also tried using the `&out TOG` behavior but that did not resume the connection.

Logging:
[20220909_zmk_win10_wake_log.txt](https://github.com/zmkfirmware/zmk/files/9541898/20220909_zmk_win10_wake_log.txt)

**Comment by petejohanson** [comment]
@vaheder can you please test again with the latest fix, and re-open if you still have the problem?

**Comment by vaheder** [comment]
Will do, thanks! I’ll probably be able to install, test, and report by the
end of next week.

**Comment by vaheder** [comment]
After a few days of testing, things look good! Thanks @droghio and @petejohanson!
