### ISSUE TITLE
Documentation page Keyboard Scan not loading

### ISSUE THREAD

**Issue by horasim** [zmkfirmware/zmk#1408]
The Docs page [Configuration/Keyboard scan](https://zmk.dev/docs/config/kscan) is not loading for me, even though all other pages work fine.

**Comment by petejohanson** [comment]
Are there any errors in the dev console of your browser? Seems to render/load just fine here in Chrome on Android.

**Comment by horasim** [comment]
I restarted my PC in the meantime,  it's working now
