### ISSUE TITLE
Vulnerability in use of win10

### ISSUE THREAD

**Issue by shuihuohuooo** [zmkfirmware/zmk#1437]
My chip is nrf52840, I updated the environment, and compiled the firmware, after I flashed, the display Bluetooth has been connected, but can not output the key code, I tried to reconnect, but bt clear also seems to be invalid, I changed back to the version to continue to use, I want to ask if there is a small partner encountered this problem

**Comment by Hello9999901** [comment]
Please join the discord server for more information. Furthermore, I do not think this is a vulnerability, just a little user error :)
