### ISSUE TITLE
When will "Realtime Keymap Updating" support?

### ISSUE THREAD

**Issue by gezhaoyou** [zmkfirmware/zmk#1447]
Hope know when will "Realtime Keymap Updating" support?

**Comment by Hello9999901** [comment]
It'll be ready when it's ready. We are working on it as part of the ZMK studio project. You are welcome to join our Discord server and check out the progress there. :)

**Comment by caksoylar** [comment]
Closing the issue as it's a question. Like Hello said, it's work in progress that is mostly in the design stage, at least as far as I can tell.

**Comment by gezhaoyou** [comment]
> Closing the issue as it's a question. Like Hello said, it's work in progress that is mostly in the design stage, at least as far as I can tell.
Okay, I got it. Thank you

**Comment by gezhaoyou** [comment]
> Closing the issue as it's a question. Like Hello said, it's work in progress that is mostly in the design stage, at least as far as I can tell.

Okay, I got it. Thank you

**Comment by gezhaoyou** [comment]
> Thank you

Thank you！
