### ISSUE TITLE
Update documentation to confirm F13-F19 works with Windows

### ISSUE THREAD

**Issue by jeep** [zmkfirmware/zmk#1476]
I am able to confirm that F13-F19 work with Windows 11. The application I use to test only recognizes F1-F19, so I cannot test F20-F24.

Please update https://zmk.dev/docs/codes#f-keys to indicate working on Windows.

(I was going to submit a PR, but got lost in the web of imports that generates the table, sorry.)

**Comment by caksoylar** [comment]
If you are still willing to do it yourself, all you need to change are the `os -> windows` values in `hid.js`, like this one here: https://github.com/zmkfirmware/zmk/blob/main/docs/src/data/hid.js#L2735

You can also check out #598 as an example.
