### ISSUE TITLE
GitHub Actions is deprecating commands and Node.js 12 actions

### ISSUE THREAD

**Issue by wj-zhe** [zmkfirmware/zmk#1501]
During the last 10 days or so, GitHub has been informing about deprecation of `save-state` and `set-output` commands and removing Node.js 12 in favor of Node.js 16. Is ZMK going to do something with it ?

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/13248460/197003263-e288ae1d-24e0-4833-ab4d-9ef0ad50600b.png">

**Comment by caksoylar** [comment]
See #1491 which also tackles this.
