### ISSUE TITLE
Question: How to map a key to tap for sticky layer1 and hold for momentary layer2?

### ISSUE THREAD

**Issue by pujvz** [zmkfirmware/zmk#1505]
I would like to map a thumb key to have tap for sticky layer (layer1) and hold for a different momentary layer (layer2). How would I go about doing this?

**Comment by petejohanson** [comment]
Create a custom hold-tap: https://zmk.dev/docs/behaviors/hold-tap

With something like `bindings = <&mo &sl>;`

**Comment by pujvz** [comment]
Thanks. Sorry if this is a dumb question. Can I put this directly into my .keymap file? 
```
/ {
    behaviors {
        mo_sl: behavior_mo_sl {
            compatible = "zmk,behavior-hold-tap";
            label = "mo_sl";
            #binding-cells = <2>;
            flavor = "hold-preferred";
            tapping-term-ms = <200>;
            bindings = <&mo>, <&sl>;
        };
    };

    keymap {
        compatible = "zmk,keymap";
        default_layer {
            bindings = <
                &mo_tog 2 1     // &mo 2 on hold, &sl 1 on tap
            >;
        };
    };
};
```

**Comment by petejohanson** [comment]
> Thanks. Sorry if this is a dumb question. Can I put this directly into my .keymap file? 

That's right 

> ```
> / {
>     behaviors {
>         mo_sl: behavior_mo_sl {
>             compatible = "zmk,behavior-hold-tap";
>             label = "mo_sl";
>             #binding-cells = <2>;
>             flavor = "hold-preferred";
>             tapping-term-ms = <200>;
>             bindings = <&mo>, <&sl>;
>         };
>     };
> 
>     keymap {
>         compatible = "zmk,keymap";
>         default_layer {
>             bindings = <
>                 &mo_tog 2 1     // &mo 2 on hold, &sl 1 on tap
>             >;
>         };
>     };
> };
> ```

Should be `&mo_sl` though at the end.

**Comment by pujvz** [comment]
Thank you so much for pointing me in the right direction! It works exactly as described.
