### ISSUE TITLE
Documentation: Confusing typo in hold-tap documentation image

### ISSUE THREAD

**Issue by dcolestock** [zmkfirmware/zmk#1558]
This [SVG image](https://github.com/zmkfirmware/zmk/blob/main/docs/docs/assets/hold-tap/comparison.svg) from the hold-tap documentation has a typo that makes the document less clear.  In the bottom case of the Balanced column, it says "Output: J" when it should say "Output: fj" to match the diagram, so its telling you the wrong output that will occur in that case.

**Comment by dxmh** [comment]
Thanks. This has now been fixed with https://github.com/zmkfirmware/zmk/pull/1560.
