### ISSUE TITLE
docs: Setup instructions for macOS on Apple silicon

### ISSUE THREAD

**Issue by dxmh** [zmkfirmware/zmk#1569]
The `gcc-arm-embedded` requirement for ZMK/Zephyr 3.0 on macOS seems to be available for x86-64 host architecture only ([source](https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads)); it is not available for AArch64 macOS hosts (i.e. Macs with Apple silicon, such as M1 and M2). 

According to a quick search on the ZMK Discord server, Apple silicon users aren't having much luck running it via Rosetta.

It would be good to document this limitation with the [macOS setup instructions](https://github.com/zmkfirmware/zmk/blob/001105e31844f0f59b82a2e71a4c3ada980b931b/docs/docs/development/setup.md#gnu-arm-embedded-1) and possibly suggest an alternative for AArch64 macOS hosts (such as Docker (https://github.com/zmkfirmware/zmk/pull/879), or the [Zephyr SDK for macOS](https://github.com/zephyrproject-rtos/sdk-ng#releases)).

**Comment by Hello9999901** [comment]
I have a PR for something similar right now. I can add this in with more verbose detail.

**Comment by caksoylar** [comment]
This is now covered by #1621, which links to Zephyr docs that includes specific instructions for Apple Silicon.
