### ISSUE TITLE
BUG: keycode RBRC is always sent shifted

### ISSUE THREAD

**Issue by Zeioth** [zmkfirmware/zmk#1591]
Could you check out this keycode is working correctly? I tried it on my base layer with

    sudo showkey

And it's always sent as shifted

![screenshot_2022-12-15_15-31-48_586725784](https://user-images.githubusercontent.com/3357792/207894988-4521e5c9-8e08-41bb-af65-ae74cd47d48a.png)
Same keycode in ZMK and QMK

**Comment by MvEerd** [comment]
RBRC means 'Right Brace' in ZMK but seemingly refers to 'Right Bracket' in QMK

![image](https://user-images.githubusercontent.com/12560315/207923588-10b9782d-880d-4289-8c15-f2ae7c90b2bf.png)

`RBKT` would be the equivalent in ZMK
