### ISSUE TITLE
Cannot roll PLUS EQUAL

### ISSUE THREAD

**Issue by pujvz** [zmkfirmware/zmk#1766]
I am unable to roll `PLUS` and `EQUAL`. 
- Expected output: `+=`
- Actual output: `+`

In order to achieve the desired output `+=`, `PLUS` must be released prior to pressing `EQUAL`. The same is true in reverse for `=+`.

This behavior also occurs when I try to roll `MINUS` and `UNDER`. I am aware that `KP_PLUS`, `KP_EQUAL`, `KP_MINUS` are a workaround, but this is not an option for me because the software I use for work incorrectly interprets these codes.

**Comment by caksoylar** [comment]
This looks like a duplicate of #1076.

**Comment by pujvz** [comment]
Thanks @caksoylar . Yes, this is a duplicate of #1076 . I did not find this issue when searching for the original issue.
