### ISSUE TITLE
subsequent key is capitalized when rolling over from a shifted key

### ISSUE THREAD

**Issue by eisukeesaki** [zmkfirmware/zmk#1798]
## The issue

input: `|`, `/`
expected output: `|/`
actual output: `?/`

## How the problematic behavior can be reproduced

https://github.com/zmkfirmware/zmk/assets/33922926/85a8b309-4b4d-4f3d-94a6-b08fb1c5860b

### What is done in the video:

**1. Demonstrate workaround:**
* key-down `|`
* wait
* key-up `|`
* key-down `/`
* wait
* key-up `/`

**2. Demonstrate the problematic behavior:**
* key-down `|`
* key-down `/`
* key-up `/`
* key-up `|`

### Other way to reproduce the problematic behavior:
* key-down `|`
* key-down `/`
* key-up `|`
* key-up `/`

## IMPORTANT NOTE

Note that I am not actually pressing the shift key to send the `|` key code, since the first physical key that I am pressing in the demo is mapped to `BACKSLASH`, which seems to automatically send `left_shift` to the host.

## Question

Is there a way to configure the firmware so that I can roll over from `|` to `/` and still get `|/`?

**Comment by caksoylar** [comment]
Closing since #1076 should fix this, please reopen if it is still an issue.
