### ISSUE TITLE
GRAVE and NUBS are inverted

### ISSUE THREAD

**Issue by dolie** [zmkfirmware/zmk#1861]
Hello,
On MacOS ISO keyboard, the keycodes GRAVE and NUBS are kind of inverted :   
<img width="267" alt="Capture d’écran 2023-07-10 à 11 04 01" src="https://github.com/zmkfirmware/zmk/assets/18349922/af50c9ba-3fe2-42be-8deb-b03f50beeeb2">
**On first screen it types `§ ±`**  
  
<img width="267" alt="Capture d’écran 2023-07-10 à 11 04 42" src="https://github.com/zmkfirmware/zmk/assets/18349922/671dbd5b-9acf-4116-8582-04bf7feeda13">  

**On second screen it types** ` ~` and backtick 

Despite the fact that visual keyboard indicates the correct key is pressed.

If I press the key via visual keyboard, the correct character is written.

https://github.com/zmkfirmware/zmk/assets/18349922/298dc429-655b-4e92-9f23-90b85550c05b

**Comment by caksoylar** [comment]
I think they might be getting swapped depending on what you do when the OS prompts you to select the kind of keyboard on first pairing/reconnect. That being said I don't use mac OS, if any users can chime in that could be great.

**Comment by bartlomiejmucha** [comment]
On my Kinesis Advantage 360 Pro, using this keymap the GRAVE works fine. https://github.com/bartlomiejmucha/Adv360-Pro-ZMK/blob/my-customisation-v3/config/adv360.keymap

**Comment by dolie** [comment]
Alright, thank you guys, 🙏
It seems to be specific to keyboard config on OS, as mentioned by @caksoylar .
