### ISSUE TITLE
I dont known what is possibly wrong

### ISSUE THREAD

**Issue by KaciMaci** [zmkfirmware/zmk#1868]
I been triing to make the code for my first handwired keyboard and after a lot of trial and error i am not capabol of finding the solution

run: [https://github.com/KaciMaci/Cu7/actions/runs/5558588046](url)

**Comment by caksoylar** [comment]
I'd recommend creating a #help-forum post in the [Discord](https://zmk.dev/community/discord/invite) for user support. It gets difficult to debug issues over Github comments.
