### ISSUE TITLE
an onboard nice!nano

### ISSUE THREAD

**Issue by marcus571** [zmkfirmware/zmk#1877]
I made a keyboard PCB. Basically I copied everything from Nice!Nano V2 schematic. But I wannt a onboard controller Keyboard. 
So I skipped the Pro Micro Interconnector and connected everything directly to nRF52840. Then I tried to create ZMK firmware for my keyboard, and here is what I did:
1. Created a repository from nice!60(because it is also a onboard controller keyboard)
2. Forked zmkfirmware/zmk
3. Modify my zmk/app/boards/arm/nace60/nice60.dts according to my own key maxtrix
4. Modify my nice60/config/nice60.keymap

Now when I connect the PCB to the computer via USB, everything is normal and the Bluetooth connection is also working, except the battery is not charging. When I disconnect the USB, the Bluetooth connection will also disconnect and the battery doesn't kick in to power the board.

What did I do wrong and what should I do to fix this?

**Comment by petejohanson** [comment]
That sounds like a hardware problem, not anything ZMK controls. I'd recommend hopping on our Discord server and someone there can try to help identify the issue. 

https://zmk.dev/community/discord/invite
