### ISSUE TITLE
corne: default config right half no output

### ISSUE THREAD

**Issue by DevArtK** [zmkfirmware/zmk#1882]
Having issues with getting right side of the board to work operate post flashing

Both sides get picked up by windows; auto opens the folder to drag uf2 file into

Once left side uf2 is dragged to left connected board flashes as expected
same for right

Issues arises when right side is plugged in and when typing, no key press output 
but when left side plugged in there is key press output 

Flashed left side uf2 to right side and works the same as the left

**Comment by kaiyes** [comment]
hey how did you solve it @DevArtK . I got the same issue
