### ISSUE TITLE
mod-morph + sticky shift = race condition?

### ISSUE THREAD

**Issue by prez** [zmkfirmware/zmk#1898]
Hi. This is a string resulting from smashing keys with a sticky shift key held:

`IENIENIE]]]]ENIEN]NIENIENINYU]?!H!]?HIEINIENIEEEEEIOENOE]?NIEIENINYUUUUUUU!N/??!?EIIEEI]/E////e!ENO/]]]IIENIU?!H?!!eEEI!NE!ENENIIEENUYUN]]]?NIENINUUUN]]]NHEIEINE!11?]?e?]?]?]?]???]?]??]n?]h]?I]III`

I want to draw attention to these substrings:

```
!11?
/e!
!eE
?e?
]n?
]h]
```

it seems there is some race condition happening? 

my keymap contains the following relevant mod-morph mappings:

| non-shift | shift |
|------------|-----|
| = | / |
|) | ]|
|, | ?|
|. | !|

**Comment by caksoylar** [comment]
Does the key being sticky make a difference or does it also happen when a regular shift is held? If so, this might be related to #1076.
