### ISSUE TITLE
Github action error to build a firmware to test Xiao BLE sense

### ISSUE THREAD

**Issue by mzks** [zmkfirmware/zmk#1905]
Hi, I would like to make my new keyboard with Xiao BLE sense.
I'm new to ZMK, thus I tried to build some keyboard to understand how to install the firmware.
I followed the instruction, https://zmk.dev/docs/user-setup.
I selected random shields and Xiao BLE sense MCU.
Unfortunately, password access for GitHub has been no longer available, thus I made a repository and pushed the contents of `zmk-config` into the repository, then the action was failure. 

https://github.com/mzks/zmk-config/actions/runs/5933972861/job/16090176576
https://github.com/mzks/zmk-config/actions/runs/5934098417/job/16090472782

The main error seems to be 
```
devicetree error: /kscan: undefined node label 'pro_micro'
CMake Error at /__w/zmk-config/zmk-config/zephyr/cmake/modules/dts.cmake:230 (message):
-- In: /__w/zmk-config/zmk-config/build/zephyr, command: /usr/bin/python3.8;/__w/zmk-config/zmk-config/zephyr/scripts/dts/gen_defines.py;--dts;/__w/zmk-config/zmk-config/build/zephyr/zephyr.dts.pre;--dtc-flags;'';--bindings-dirs;/__w/zmk-config/zmk-config/zmk/app/drivers/zephyr/dts/bindings;/__w/zmk-config/zmk-config/zmk/app/dts/bindings;/__w/zmk-config/zmk-config/zephyr/dts/bindings;--header-out;/__w/zmk-config/zmk-config/build/zephyr/include/generated/devicetree_generated.h.new;--dts-out;/__w/zmk-config/zmk-config/build/zephyr/zephyr.dts.new;--edt-pickle-out;/__w/zmk-config/zmk-config/build/zephyr/edt.pickle;--vendor-prefixes;/__w/zmk-config/zmk-config/zmk/app/dts/bindings/vendor-prefixes.txt;--vendor-prefixes;/__w/zmk-config/zmk-config/zephyr/dts/bindings/vendor-prefixes.txt
  gen_defines.py failed with return code: 1
Call Stack (most recent call first):
  /__w/zmk-config/zmk-config/zephyr/cmake/modules/zephyr_default.cmake:108 (include)
  /__w/zmk-config/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /__w/zmk-config/zmk-config/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:15 (find_package)
```
 during build west.

How can I solve this error?
What's better example to build macro pad with Xiao BLE?

**Comment by petejohanson** [comment]
You've chosen a shield designed for a pro-micro compatible controller. Try the `hummingbird` shield for one that works with XIAO-compatible controllers.

**Comment by mzks** [comment]
Thank you!
