### ISSUE TITLE
docs: Windows Setup: source

### ISSUE THREAD

**Issue by innovaker** [zmkfirmware/zmk#191]
https://zmkfirmware.dev/docs/dev-setup/#environment-variables

Suggests running:  `source zephyr/zephyr-env.cmd`

`source` isn't a command within cmd or Powershell.

**Comment by innovaker** [comment]
Please note that this was also flagged by Ehps: https://discordapp.com/channels/719497620560543766/719909884769992755/753516093276160001
but I think it got buried.

**Comment by chenkevinh** [comment]
For me when I setup on Windows I found the .cmd didn't work, so I skipped it and just added the GNU ARM Embedded environment variables that we have in the docs right now. Not sure what functionality that may or may not have impacted but I've been able to build boards and shields without any issues so far.
