### ISSUE TITLE
Add installation of `dfu-util` to dev setup guide

### ISSUE THREAD

**Issue by petejohanson** [zmkfirmware/zmk#197]
To support STM32 based boards, e.g. `proton_c` or `planck`, those are set to use `dfu-util` to flash them. We should update the dev setup/installation guide to include installing `dfu-util` by default. It's a small extra install, that will avoid confusion later for anyone targeting that hardware.

**Comment by shurikai** [comment]
You have to download dfu-util from https://github.com/redbear/Duo/blob/master/docs/dfu-util_installation_guide.md and put it somewhere in your path (rename to dfu-util.exe first). This will allow dfu flashing.

**Comment by petejohanson** [comment]
On macOS and Linux, you should be able to use your package manager (e.g. `brew`, `dnf`, `apt`) to install `dfu-util` as well.

**Comment by innovaker** [comment]
@petejohanson, should this be closed?
