### ISSUE TITLE
Hold-Tap configuration for multiple taps

### ISSUE THREAD

**Issue by cdarwin** [zmkfirmware/zmk#199]
I would like to tap a hold-tap key more than once and then hold it down so that the key sends multiple tap codes until I release the key again.

# Use Case:
I have a thumb key defined as a layer-tap behavior so that it sends `SPC` when tapped and enables a layer when held. I would like to tap that key once to send the tap behavior and then (roughly) immediately hold the key so that I can continue sending `SPC` until I release the key. Today, the subsequent hold of the key triggers the configured hold behavior.

# Notes:
Turning this on should probably be a user configurable boolean. The period of time between the initial tap and the subsequent hold should probably be a user configurable integer. The number of times that a tap might trigger a branch on this behavior should probably be a user configurable integer.

**Comment by okke-formsma** [comment]
closed in favor of https://github.com/zmkfirmware/zmk/issues/288
