### ISSUE TITLE
setup.sh: curl always required

### ISSUE THREAD

**Issue by innovaker** [zmkfirmware/zmk#200]
https://zmkfirmware.dev/docs/user-setup provides the option to use `wget`, presumably as an alternative to `curl`.

But it fails on line 112 and line 115 of `setup.sh` which expects `curl` to be on the system.

**Comment by CrossR** [comment]
Once https://github.com/zmkfirmware/zmk/pull/180 is in, this would mean adding a few things:

 - Change `check_exists` to include a third "don't exit, instead return true/false" param.
 - Check for `wget` as well as `curl`.
 - Add an if statement to select which to use, or print an appropriate error message and exit if neither exist.
 - If one does exist, store the chosen one to a var and swap the usage of `curl` to use that variable.
