### ISSUE TITLE
&layer-tap take LAYER as 2nd parameter?

### ISSUE THREAD

**Issue by AndreyAdrian** [zmkfirmware/zmk#2010]
Right now it only accepts: &lt (LAYER) (KEYCODE)

How can I: &lt (LAYER) (LAYER)

![image](https://github.com/zmkfirmware/zmk/assets/64794163/60bd2a59-0731-425e-8814-ef84256bb613)

**Comment by caksoylar** [comment]
Not exactly sure what you are trying to do, but if you want the tap to *toggle* a layer, then check out the "Toggle-on-Tap, Momentary-on-Hold Layers" example at https://zmk.dev/docs/behaviors/hold-tap#example-use-cases

**Comment by caksoylar** [comment]
Closing this question since there is no follow up, as a reminder the ZMK server is great for user questions: https://zmk.dev/community/discord/invite
