### ISSUE TITLE
Add missing headers

### ISSUE THREAD

**Issue by innovaker** [zmkfirmware/zmk#205]
Some existing files are missing their copyright/licensing header.

The basic template for *.c and *.h files is:
```
/*
 * Copyright (c) 2020 The ZMK Contributors
 *
 * SPDX-License-Identifier: MIT
 */
```

Clearing this up is a prerequisite for #38.

**Comment by DevMashru** [comment]
Hey, I would like to work on this.

**Comment by petejohanson** [comment]
@DevMashru Thanks! I've set you as assigned to the issue. Let me know if you have any questions while you're working on this.

**Comment by innovaker** [comment]
Thanks @DevMashru!

I've realised I probably wasn't clear enough in my original task specification.  @petejohanson, do we also want the headers in non-C files done as well (i.e. *every* file) please?

**Comment by innovaker** [comment]
@petejohanson let me know in Discord ...
https://discordapp.com/channels/719497620560543766/719544230497878116/761256624492511283
... that it's OK to merge just the `.h`/`.c` files as a first pass.

**Comment by DevMashru** [comment]
@innovaker I definitely misunderstood the issue thinking that the header was required only in C files. I am sorry but I am not really sure if I can add this to all the files, at least right now.

**Comment by innovaker** [comment]
Yeah, that's my bad.  The `.h` and `.c` files are a good start for this issue.  Thanks for doing it 👍
