### ISSUE TITLE
Does ZMK support Hall Effect Sensor based Hardware?

### ISSUE THREAD

**Issue by SnappierSoap318** [zmkfirmware/zmk#2096]
can I use ZMK for an Analog Hall effect sensor-based keyboard using the Arduino ESP32-S3?

**Comment by joelspadin** [comment]
There's no reason it couldn't be supported if you write a new key scan driver for it, but there is not currently any support for Hall effect keyboards. Also note that https://docs.zephyrproject.org/latest/boards/xtensa/esp32s3_devkitm/doc/index.html does not list the radio as a supported feature, so I'm not sure if Zephyr supports wireless on that controller yet.

(You could also ask on the Discord server. The only people watching the issues here are the code maintainers.)

**Comment by SnappierSoap318** [comment]
Arduino Nano ESP32-S3 does have Wifi and BLE, so i might need to figure out a way to add that as well. ahh thanks!

**Comment by myst729** [comment]
@SnappierSoap318 Any updates? Would like to try magnetic switches too.

**Comment by gideontonkinson** [comment]
@joelspadin I'm interested contribuitng or forking the repo and creating the key scanner driver and I need to get familiar with the ZMK project, so do you have any hints on where to get started with that? If not I'll work through it and find it eventually. @myst729 if I get anywhere on it and especially if I finish it I'll come back here and let yah know.

**Comment by joelspadin** [comment]
The existing key scan drivers are defined at https://github.com/zmkfirmware/zmk/tree/main/app/module/drivers/kscan. Reading up on [Zephyr drivers](https://docs.zephyrproject.org/latest/kernel/drivers/index.html) would also help.
