### ISSUE TITLE
iPhone Keyboard not working..

### ISSUE THREAD

**Issue by kimuno89** [zmkfirmware/zmk#2110]
It connects from one iPhone connection profile to another, but it doesn't actually do that.

Is there a way to prefer Bluetooth to connect rather than delete it when moving a profile?

If you turn off the Bluetooth function on your iPhone, the keypad will appear.

**Comment by caksoylar** [comment]
ZMK will stay connected to paired profiles, so you can quickly switch between them without a reconnection delay.

However there is a disconnect keymap binding now, please see the documentation for `BT_DISC`: https://zmk.dev/docs/behaviors/bluetooth

With that, you can switch to a different profile than the phone, then invoke `&bt BT_DISC n` where `n` is the profile index for your phone pairing.
