### ISSUE TITLE
Caps word does not deactivate sticky layer

### ISSUE THREAD

**Issue by agisga** [zmkfirmware/zmk#2133]
When I have the caps word behavior (&caps_word) as a key in a sticky layer (default &sl), the sticky layer doesn't get deactivated upon press or release of the caps word key. So, I have to wait for the sticky layer to time out before I can type the capital alphas from my base layer. I don't know if that's the intended behavior, but wouldn't it make more sense to deactivate the sticky layer immediately after caps word is pressed, because most people would activate caps word for use in conjunction with alphas on the base layer?

**Comment by caksoylar** [comment]
Sticky keys are only deactivated via keycodes, i.e. key press/releases that are sent to the connected device. They aren't deactivated via *bindings*, i.e. they wouldn't be affected by a layer change, or caps word activation (which doesn't send the host anything, only modifies an internal state). This can probably be clarified better in the docs.

You could try working around it by having a macro that toggles caps word and also sends a dummy keycode (like `K_CANCEL`) to cancel the sticky key.

**Comment by agisga** [comment]
> They aren't deactivated via _bindings_, i.e. they wouldn't be affected by a layer change, or caps word activation (which doesn't send the host anything, only modifies an internal state). This can probably be clarified better in the docs.

Thanks for the clarification! Wouldn't it be better though if sticky layers were deactivated by bindings also? From what you describe, it sounds like this is not just a limitation for putting a caps-word key on a sticky layer, but also, for example, for accessing other layers from a sticky layer, or chaining sticky layers (e.g., sticky layer Sym1 has a key to activate sticky layer Sym2). I agree that it would be good to clarify this in the docs, as it makes certain keymaps impossible with the default sticky behaviors without extra steps.

**Comment by caksoylar** [comment]
I didn't have a hand in the design or implementation, but I can see there are trade-offs either way: If you have sticky keys/layers deactivate on any key position press (as opposed to the emission of a keycode event), then e.g. you wouldn't be able to do
- Activate `&sk LCTRL`
- Activate your function layer with `&mo FUN`
- Send ctrl+F1 via tapping `&kp F1` on the function layer

So making the deactivation condition configurable might be the best solution.

**Comment by agisga** [comment]
Great point, thank you. Agree that configurability then would be best. For instance, so that behavior can be set differently for sticky mods vs. sticky layers.

Should I close this issue for now since this isn't a bug?

**Comment by caksoylar** [comment]
If you like to you can close it. Or you can convert it to a feature request by describing what you want with example use cases.
