### ISSUE TITLE
Feature: Basic power management functionality:

### ISSUE THREAD

**Issue by petejohanson** [zmkfirmware/zmk#214]
* Sleep after a certain timeout.
* Turning off OLEDs when sleeping
* Wakeup on key press
* Investigate using PORT events for matrix interrupts, for improved power saving.
* Ability to disable VCC on nice!nano via MOSFET pin.

**Comment by megamind4089** [comment]
I am working on the following first:
**Ability to disable VCC on nice!nano via MOSFET pin.**

**Comment by petejohanson** [comment]
I have started work on deep sleep, starting w/ the move to PORT events on nrf52 in #211

**Comment by Nicell** [comment]
I have added support for ext-power (VCC cut off) switching off when going into deep sleep in #417

**Comment by petejohanson** [comment]
This... Is all done.
