### ISSUE TITLE
Assertion failed: The toolchain is unable to build a dummy C file

### ISSUE THREAD

**Issue by LXF-YZP** [zmkfirmware/zmk#2162]
The following problems occur when installing the zmk local environment，
[CMakeError.log](https://github.com/zmkfirmware/zmk/files/14241644/CMakeError.log)
[CMakeOutput.log](https://github.com/zmkfirmware/zmk/files/14241647/CMakeOutput.log)

`Loading Zephyr default modules (Zephyr base).
-- Application: /Users/luxiaofeng/zmk/app
-- CMake version: 3.22.3
-- Found Python3: /Users/luxiaofeng/zephyrproject/.venv/bin/python3 (found suitable version "3.11.4", minimum required is "3.8") found components: Interpreter
-- Cache files will be written to: /Users/luxiaofeng/Library/Caches/zephyr
-- Zephyr version: 3.5.0 (/Users/luxiaofeng/zmk/zephyr)
-- Found west (found suitable version "1.2.0", minimum required is "0.14.0")
-- Adding /Users/luxiaofeng/zmk/app/boards/shields/kyria
-- Using keymap file: /Users/luxiaofeng/zmk/app/boards/shields/kyria/kyria.keymap
-- Board: nice_nano_v2
-- Shield(s): kyria_left
-- ZEPHYR_TOOLCHAIN_VARIANT not set, trying to locate Zephyr SDK
-- Found host-tools: zephyr 0.16.3 (/Users/luxiaofeng/zephyr-sdk-0.16.3)
-- Found toolchain: zephyr 0.16.3 (/Users/luxiaofeng/zephyr-sdk-0.16.3)
-- Found Dtc: /usr/local/bin/dtc (found suitable version "1.6.1", minimum required is "1.4.6")
-- Found BOARD.dts: /Users/luxiaofeng/zmk/app/boards/arm/nice_nano/nice_nano_v2.dts
-- Found devicetree overlay: /Users/luxiaofeng/zmk/app/boards/shields/kyria/kyria_left.overlay
-- Found devicetree overlay: /Users/luxiaofeng/zmk/app/boards/shields/kyria/boards/nice_nano_v2.overlay
-- Found devicetree overlay: /Users/luxiaofeng/zmk/app/boards/shields/kyria/kyria.keymap
-- Generated zephyr.dts: /Users/luxiaofeng/zmk/app/build/left/zephyr/zephyr.dts
-- Generated devicetree_generated.h: /Users/luxiaofeng/zmk/app/build/left/zephyr/include/generated/devicetree_generated.h
-- Including generated dts.cmake file: /Users/luxiaofeng/zmk/app/build/left/zephyr/dts.cmake
/Users/luxiaofeng/zmk/app/build/left/zephyr/zephyr.dts:57.25-62.5: Warning (unique_unit_address_if_enabled): /soc/clock@40000000: duplicate unit-address (also used in node /soc/power@40000000)
/Users/luxiaofeng/zmk/app/build/left/zephyr/zephyr.dts:340.21-344.5: Warning (unique_unit_address_if_enabled): /soc/acl@4001e000: duplicate unit-address (also used in node /soc/flash-controller@4001e000)

warning: Deprecated symbol NRF_STORE_REBOOT_TYPE_GPREGRET is enabled.

Parsing /Users/luxiaofeng/zmk/app/Kconfig
Loaded configuration '/Users/luxiaofeng/zmk/app/boards/arm/nice_nano/nice_nano_v2_defconfig'
Merged configuration '/Users/luxiaofeng/zmk/app/prj.conf'
Merged configuration '/Users/luxiaofeng/zmk/app/boards/shields/kyria/kyria_left.conf'
Configuration saved to '/Users/luxiaofeng/zmk/app/build/left/zephyr/.config'
Kconfig header saved to '/Users/luxiaofeng/zmk/app/build/left/zephyr/include/generated/autoconf.h'
-- Found GnuLd: /Users/luxiaofeng/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/../lib/gcc/arm-zephyr-eabi/12.2.0/../../../../arm-zephyr-eabi/bin/ld.bfd (found version "2.38")
-- The C compiler identification is GNU 12.2.0
-- The CXX compiler identification is GNU 12.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /Users/luxiaofeng/zephyr-sdk-0.16.3/arm-zephyr-eabi/bin/arm-zephyr-eabi-gcc
CMake Error at /Users/luxiaofeng/zmk/zephyr/cmake/modules/extensions.cmake:2252 (message):
  Assertion failed: The toolchain is unable to build a dummy C file.  Move
  /Users/luxiaofeng/Library/Caches/zephyr, re-run and look at CMakeError.log
Call Stack (most recent call first):
  /Users/luxiaofeng/zmk/zephyr/cmake/modules/kernel.cmake:145 (assert)
  /Users/luxiaofeng/zmk/zephyr/cmake/modules/zephyr_default.cmake:138 (include)
  /Users/luxiaofeng/zmk/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:66 (include)
  /Users/luxiaofeng/zmk/zephyr/share/zephyr-package/cmake/ZephyrConfig.cmake:92 (include_boilerplate)
  CMakeLists.txt:8 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/luxiaofeng/zmk/app/build/left/CMakeFiles/CMakeOutput.log".
See also "/Users/luxiaofeng/zmk/app/build/left/CMakeFiles/CMakeError.log".
FATAL ERROR: command exited with status 1: /usr/local/bin/cmake -DWEST_PYTHON=/Users/luxiaofeng/zephyrproject/.venv/bin/python3 -B/Users/luxiaofeng/zmk/app/build/left -GNinja -DBOARD=nice_nano_v2 -DSHIELD=kyria_left -S/Users/luxiaofeng/zmk/app`

**Comment by joelspadin** [comment]
It would help to know more about your environment. From the paths, I'm guessing mac? What hardware are you running this on?
