### ISSUE TITLE
Asymmetric split keyboard

### ISSUE THREAD

**Issue by berikiushi** [zmkfirmware/zmk#2163]
Is it possible to create firmware for an asymmetric split keyboard whose halves have different wiring boards and use different controller pins for columns and rows?

left: 29 keys + roll encoder + nice!nano + nice!view
right: 43 keys + roll encoder + nice!nano

![image](https://github.com/zmkfirmware/zmk/assets/3989247/86d98964-ad44-4d04-8aa0-120d5826f7d4)

![image](https://github.com/zmkfirmware/zmk/assets/3989247/f8567850-ed03-4699-8908-0d2bccea2d17)

**Comment by petejohanson** [comment]
Of course. In this case the only thing you'd really have in the common .dtsi would be the matrix transform.

**Comment by berikiushi** [comment]
> Of course. In this case the only thing you'd really have in the common .dtsi would be the matrix transform.

Thanks for the reply, it's encouraging.
Just now I have found several examples of asymmetric keyboards in the repository, I will study them in more detail.
