### ISSUE TITLE
Missing documentation regarding peripheral battery level monitoring

### ISSUE THREAD

**Issue by dennisorlando** [zmkfirmware/zmk#2166]
Hi,
#2045 is merged but the [website](https://zmk.dev/docs/config/battery) doesn't mention the possibility to monitor both the batteries of a split keyboard.

**Comment by caksoylar** [comment]
It is documented in https://zmk.dev/docs/config/system#split-keyboards but might be good to have a pointer there.

**Comment by dennisorlando** [comment]
Hmm I'm currently writing it in the main page, should I reconsider what I'm doing?

**Comment by dennisorlando** [comment]
Update: I've push requested #2167 since mentioning the difficulties of reading both values is probably worthwhile
