### ISSUE TITLE
Documentation: more warning for Kconfig.shield

### ISSUE THREAD

**Issue by 01110** [zmkfirmware/zmk#2183]
Hello!

I've just created a new keyboard shield based on the documentation: https://zmk.dev/docs/development/new-shield

I have written an extra space character between "shields_list_contains," and "my_board":

```
config SHIELD_MY_BOARD
    def_bool $(shields_list_contains, my_board)
```

The valid format is without space:

```
config SHIELD_MY_BOARD
    def_bool $(shields_list_contains,my_board)
```

The caused error was that the board does not advertised itself over bluetooth. After 2 hours of debugging and reading solved issues in the discord server's history I managed to fix the issue. The documentation does warn about that "my_board" string should be set properly, but as a person not familiar with writing Kconfig files I went over it at least 5 times (and the error is hard to find visually).

I think other people will mess this up in the future, so I suggest to add a warning or a sentence in the documentation that there should be absolutely no space where I added.

**Comment by caksoylar** [comment]
It would be worth adding a warning box to that section, given I personally gave this advice tens of times over Discord when debugging issues.

**Comment by huber-th** [comment]
@caksoylar I took a stab at this update to the documentation. Please let me know if you think the wording or the location of the warning box should be changed.
