### ISSUE TITLE
ZMK crashes on key spam. 

### ISSUE THREAD

**Issue by Na-Cly** [zmkfirmware/zmk#221]
ZMK crashes when keys are pressed too rapidly. 

At minimum 1 reset is required to fix once it's occurred. 

Last time I watched it on the debugger the the failed to send message count hit around 40 and then the debugger stopped outputting lines. 

This is a very repeatable issue, so no issue testing it.

**Comment by leejunseok** [comment]
I am seeing this issue as well, but only in the peripheral side of my Corne + nice nanos. I've spammed keys on my left half and could not get it to reproduce on that half at all.

Interesting notes:
- the debugger stops immediately, not even finishing the current line of output
- sometimes a key is stuck held and sometimes not
- the left half continues to work in some cases
- output from keys on the right half seems to slow down before the freeze

**Comment by bcat** [comment]
I see stuck keys periodically on the primary (central?) side as well, e.g., G getting stuck down on the left side of my Crkbd.

**Comment by ant0ncuranz** [comment]
I am experiencing the same issue (using a non-split keyboard with a nice-nano).
It seems only to happen when connected via BLE, no issues with USB.

**Comment by wyolland** [comment]
Can confirm that I get the same issue on a Quefrency rev1 split. 
If I only spam keys on either side of the split, then I cannot reproduce this issue.
As soon as I start to spam keys on both sides, one of the keys on the right side repeats indefinitely until I reset the board.

**Comment by Slusho64** [comment]
I can reproduce this issue over and over in a few seconds with my quefrency by spamming both sides, with the effect of a key held on the left side, the right side, or the keyboard doesn't input anything, until reset.

**Comment by petejohanson** [comment]
So, some additional notes: I *cannot* reproduce this over USB. I believe our semaphore use there may be avoiding issues, and we don't have the same in place for the GATT notifications.

**Comment by joelspadin** [comment]
There was another report on Discord that spinning an encoder too fast also triggers this, but only when wireless.

**Comment by 4pplet** [comment]
I've also been experiencing this. Only on BT.
