### ISSUE TITLE
 Any membrane keyboards with ZMK support

### ISSUE THREAD

**Issue by korpe1** [zmkfirmware/zmk#2215]
Are there any membrane keyboards that ZMK supports?

**Comment by caksoylar** [comment]
No, at least not that I know of. Membrane keyboards aren't really DIY territory, and among mass market manufacturers only ergonomic keyboard vendors like Kinesis and MoErgo seems to be using ZMK.

**Comment by korpe1** [comment]
> No, at least not that I know of. Membrane keyboards aren't really DIY territory, and among mass market manufacturers only ergonomic keyboard vendors like Kinesis and MoErgo seems to be using ZMK.

Can we add support for any membrane keyboard?

**Comment by caksoylar** [comment]
Assuming they use a matrix or direct pin, sure. There is no anti-ghosting functionality in ZMK, and it might be necessary since they don't use diodes. #1533 and #1664 have been attempts at that.
