### ISSUE TITLE
Action Build Error on default configuration

### ISSUE THREAD

**Issue by SparrowMike** [zmkfirmware/zmk#2219]
Hi!

Got my first corne with Nordic nRF52840 DK ( that's what I was told )

I have tried several times and always get the same result when building, waste quite a bit of time looking around and can't find anyone else having the same issue 

https://github.com/SparrowMike/zsk-config-corne/actions/runs/8393067110/job/22987218007

**Comment by englmaxi** [comment]
Are you sure you use a [Nordic nRF52840 DK](https://www.nordicsemi.com/Products/Development-hardware/nRF52840-DK)?

The Corne is designed to be used with a [Pro Micro compatible board](https://zmk.dev/docs/hardware#pro_micro), which the Nordic DK is not. That's why your build failed.

**Comment by SethMilliken** [comment]
You almost certainly have a `nice_nano_v2` clone not this: https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/zephyr/boards/arm/nrf52840dk_nrf52840/doc/index.html

**Comment by SparrowMike** [comment]
Thanks @englmaxi and @SethMilliken yes I didn't think its the [Nordic nRF52840 DK](https://www.nordicsemi.com/Products/Development-hardware/nRF52840-DK) but that's what I was told to use when configuring 😅

Looking again at the messages with the seller he said the MCU was Nrf52840ble - however looking at the pictures it doesn't look the same as the top results from google.

![IMG_7639_2](https://github.com/zmkfirmware/zmk/assets/69448825/eb8c1507-3bd4-4b02-ab9d-ec9c84400010)
![IMG_7640_2](https://github.com/zmkfirmware/zmk/assets/69448825/30bf9a49-8b79-4e57-9314-aa4b895b2c09)

**Comment by SparrowMike** [comment]
I think this must be some sort of Supermini nRF52840 copy? hahaha honestly no clue

But it should be safe just to flush it with `nice_nano_2` right ?

**Comment by englmaxi** [comment]
according to [this](https://github.com/joric/nrfmicro/wiki/Alternatives#52840nano), it uses the `nice_nano_v2` shield, yes.

**Comment by SparrowMike** [comment]
I'm embarresed 😅

Thanks loads for your time, will give this a go. 

cheers!
