### ISSUE TITLE
Combo behavior to behave differently when SHIFT is held?

### ISSUE THREAD

**Issue by christoofar** [zmkfirmware/zmk#2223]
Hello.    I have vertical combos set for typing `( ) < > [ ] { }` but I was wanting to speed up the typing of empties (e.g. the `()` in `main()`), by holding down SHIFT while hitting `)` as I have SHIFT on the left-hand and `)` is a vertical combo on the top and home row index keys.

I'm not sure how to go about modifying what I have.

https://github.com/christoofar/zmk-config-corne/blob/master/config/corne.keymap

**Comment by caksoylar** [comment]
You would want to assign a mod morph behavior to the combo bindings value, please see the docs on mod morph for how to write the former.

**Comment by christoofar** [comment]
Thank you!
