### ISSUE TITLE
Upgrade to Zephyr 2.4.0

### ISSUE THREAD

**Issue by petejohanson** [zmkfirmware/zmk#223]
Zephyr 2.4.0 was just released, which includes lots of fixes for the BLE stack, in addition to other changes.

We should explore updating, perhaps once that release has had time to "settle".

- we currently have two patches on top of 2.3.0 that need evaluation:
  - USB send fix, may be unneeded with the semaphore fixes we added.
  - some LD fixes for our native posix tests. I attempted to upstream these, but I think they were reverted. Will need further investigation.

We also have some interesting CMake usage, we'll need to test if change to Zephyr's build impact ours.

**Comment by benjizhai** [comment]
https://github.com/benjizhai/zmk/tree/zephyr-2.4.0

USB mode works but somehow bluetooth does not (connection dropping 0x08). Need to explore further.

HW: nrfmicro_13 on lily58

**Comment by petejohanson** [comment]
@benjizhai Thanks for doing some legwork on this! I would like to get a few more things stable and rolled out before we disrupt things w/ the Zephyr upgrade. I will *definitely* be looking at your branch when we get there though.
