### ISSUE TITLE
Wake up about soft-off

### ISSUE THREAD

**Issue by Eloy98** [zmkfirmware/zmk#2247]
I am very happy that zmk has added the soft-off function. I opened the soft-off configuration and added &soft-off to the keyboard. Is it possible to wake up the keyboard by pressing the keys on the matrix?Here is my keyboard code link：
https://github.com/Eloy98/le_chiff_ble_config/blob/rev1/config/le_chiff_ble.keymap
I hope the zmk documentation can provide a schematic for this
https://zmk.dev/docs/features/soft-off#matrix-integrated-hardware-combo

**Comment by caksoylar** [comment]
Thanks @lesshonor, closing.
