### ISSUE TITLE
Soft off only turn off the left side of my Corne split keyboard

### ISSUE THREAD

**Issue by picrots** [zmkfirmware/zmk#2274]
I recently built a wireless Corne keyboard on the original v3 PCB design which doesn't have a power switch.

To turn my keyboard off I setup a keymap to trigger the Soft Off feature and it does work however only on the master side and the right side stays up.

I tried to create additional key map on the right side but that also only turn the left side off.

I am using Corne V3 and Nice!nano controller. My last build was through github action on 15th Apr 2024.

**Comment by omalishe-pearl** [comment]
Same here, also there is a discord thread with some other people having same problem: https://discord.com/channels/719497620560543766/1225441220311126106/1225441220311126106

**Comment by picrots** [comment]
This problem has not been resolved for me yet and right side of my Corne stays awake.
Build date: 10 May 2024 (using github actions)

**Comment by GermanG** [comment]
Can you check #2300? Also use my ZMK repo to verify if that's your case
