### ISSUE TITLE
fix: `MACRO_PLACEHOLDER` causes `parse error: expected number or parenthesized expression`

### ISSUE THREAD

**Issue by jjangga0214** [zmkfirmware/zmk#2379]
Hi!

I have a config like this.
(Other details are omitted for brevity.)

```
/ {
    macros {
        bt_to: bt_to {
            label = "bt_to";
            compatible = "zmk,behavior-macro-two-param";
            #binding-cells = <2>;
            bindings
                = <&macro_param_1to2>
                , <&bt BT_SEL MACRO_PLACEHOLDER>
                , <&macro_param_2to1>
                , <&to MACRO_PLACEHOLDER>;
        };
    };
};
```

And an error occurs on build. 

```sh
devicetree error: path/to/adv360.keymap:253 (column 26): parse error: expected number or parenthesized expression
```

It seems use of `MACRO_PLACEHOLDER` causes the error.

**Comment by ReFil** [comment]
On an advantage 360 pro specific note, V2.0 config repositories are very outdated by now and as a result several features such as macros are not properly supported in it. There is a migration guide to the new v3.0 repositories available here: https://github.com/KinesisCorporation/Adv360-Pro-ZMK/blob/V3.0/UPGRADE.md

**Comment by jjangga0214** [comment]
Oh, thank you very much!
