### ISSUE TITLE
Cannot create a layer with only behaviors with no parameters

### ISSUE THREAD

**Issue by joelspadin** [zmkfirmware/zmk#241]
Creating a layer in a keymap with nothing but behaviors like &none, &trans, or &reset causes an error in Zephyr.

See https://github.com/zephyrproject-rtos/zephyr/issues/28709 (which has been fixed).

**Comment by tominabox1** [comment]
Has this been pulled into ZMK yet? @petejohanson

**Comment by 310weber** [comment]
I ran into this issue today so can confirm it still exists in main branch.

**Comment by bcat** [comment]
It looks like this is fixed now. I've made a layer with just `&none` behaviors in https://github.com/bcat/zmk-config/commit/0bc448295927aeeac89363f8ed91db47184b6a61 and it compiles just fine. (Maybe it was fixed in the Zephyr 2.5 update?)
