### ISSUE TITLE
Feature request: Hardware troubleshooting shield

### ISSUE THREAD

**Issue by Nick-Munnich** [zmkfirmware/zmk#2410]
For hardware troubleshooting, it would be convenient to have a shield in a similar vein to `settings_reset` which behaves as follows:
1. Configures all GPIO pins as input with a high pullup
2. Whenever any GPIO pin is pulled low (connected to ground), set all other GPIO pins to low while the triggered GPIO pin is low

Because some boards have shorts between GPIO pins and reset, there needs to be a mechanism in devicetree to exclude some GPIO pins from the above behaviour, rather leaving them hanging.

**Comment by caksoylar** [comment]
Maybe we can start with a simpler version without 2.? e.g. a Pro Micro version with direct pins mapping to a macro each that prints the pro micro pin number. And another for the Xiao interconnect perhaps.

**Comment by Nick-Munnich** [comment]
That would probably be a better approach entirely - somehow the possibility of using the usb connection completely slipped in my mind.
