### ISSUE TITLE
CONFIG_ZMK_WIDGET_LAYER_STATUS not working

### ISSUE THREAD

**Issue by quiquos** [zmkfirmware/zmk#2467]
A few days ago, CONFIG_ZMK_WIDGET_LAYER_STATUS stopped showing the layer we are in.

this is my conf file:
```
CONFIG_ZMK_KEYBOARD_NAME="Quiquos Corne"
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_WIDGET_LAYER_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS=y
CONFIG_ZMK_WIDGET_BATTERY_STATUS_SHOW_PERCENTAGE=y
CONFIG_ZMK_WIDGET_OUTPUT_STATUS=y
CONFIG_ZMK_WIDGET_WPM_STATUS=y
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_PM_SOFT_OFF=y
```

If I flash a version from, for example, a month ago, it works great.
The same code compiled last week won't show the layer number we are in.

I tried something I read that CONFIG_ZMK_WIDGET... are no longer needed to put in conf file, but even so, it doesn't work.

My keyboard is the Split Corne wireless connected via BT (also with cable, layer is not displayed)

**Comment by caksoylar** [comment]
Does it work if you add `display-name` properties to the layer nodes? e.g. `display-name = "Base";`

**Comment by caksoylar** [comment]
No, it is an additional property that goes in the node like I mentioned above. See examples in https://github.com/zmkfirmware/zmk/blob/1c48f64730a479115ae827c342c1063b2b8e93ca/app/boards/shields/reviung34/reviung34.keymap#L28

**Comment by quiquos** [comment]
Nice, it worked.

Actually, it's even better, because I thought that I could only display a number as a layer "name" to be displayed, and now I have the name I want.

Thanks

**Comment by Grazfather** [comment]
I added this to the docs in #2460

**Comment by petejohanson** [comment]
Flease give https://github.com/zmkfirmware/zmk/pull/2491 a test.

**Comment by caksoylar** [comment]
Closing given #2491 is merged, please re-open if still an issue.
