### ISSUE TITLE
`zmk,matrix-transform` invalidates firmware build

### ISSUE THREAD

**Issue by DanielAtCosmicDNA** [zmkfirmware/zmk#2489]
As can be seen on https://github.com/typeractivexyz/corne-wireless-5-col-view-zmk-config/issues/6. The option `zmk,matrix-transform` of https://zmk.dev/docs/config/kscan#devicetree invalidates the firmware build with the following build error:

>    17 | #error "To use physical layouts, remove the chosen `zmk,matrix-transform` value."
>       |  ^~~~~

**Comment by petejohanson** [comment]
@DanielAtCosmicDNA Can you please give #2490 a try?

**Comment by DanielAtCosmicDNA** [comment]
> @DanielAtCosmicDNA Can you please give #2490 a try?

Sure. I have just retriggered [the build](https://github.com/CosmicDNA/corne-wireless-5-col-view-zmk-config/actions/runs/10813360993) and now it is generating the firmware.
