### ISSUE TITLE
docs: Add multi-platform support to Basic Setup instructions

### ISSUE THREAD

**Issue by innovaker** [zmkfirmware/zmk#26]
For:
- Linux (or Ubuntu if easier)
- Windows
- macOS
- Raspberry OS

Could perhaps leverage these examples:
- https://v2.docusaurus.io/docs/markdown-features/#multi-language-support-code-blocks
- https://docs.zephyrproject.org/latest/getting_started/index.html

From: https://discord.com/channels/719497620560543766/719565084208398406/721742604055740488

**Comment by petejohanson** [comment]
This is done.
