### ISSUE TITLE
The right split keyboard V1 connected by BLE cannot type the line of keys 'yuiop'.

### ISSUE THREAD

**Issue by laiminhtrung1997** [zmkfirmware/zmk#2710]
I bought a SOFLE V1 keyboard last week. I don’t like the wired connection between the two halves of the split keyboard, so I decided to customize it to use wireless with BLE. To achieve this, I purchased two Supermini NRF52840 modules to make the keyboard wireless. I flashed them with ZMK firmware.

The left half was successfully configured and can connect to my laptop via BLE. The right half was also successfully configured and can connect to the left half. However, the entire second row from the top on the right side doesn’t work—it doesn’t type at all.

After resetting the right half, the issue persists: the second row still doesn’t type. Moreover, when I press any key other than the ones in that row, the string "yuio" is unexpectedly typed, followed by the correct character. For example, after resetting the keyboard, if I press the "1" key, the output on my laptop is "yuio1."

I even tried using a new NRF52840 module, but the problem still occurs. Has anyone else encountered this issue? I would greatly appreciate any help or suggestions.
![Image](https://github.com/user-attachments/assets/81fd3381-5c7b-46a3-b3a1-3e75481f1844)
![Image (1)](https://github.com/user-attachments/assets/01c637c2-1a37-4dff-96f9-da476ca52b96)

**Comment by caksoylar** [comment]
It looks like you asked on Discord too, which is the right place for user questions. This sounds like a hardware issue so I'll close and we can continue debugging on Discord.
