### ISSUE TITLE
When adding a pointing device, the error "undefined reference to `__device_dts_ord_18'" appears.

### ISSUE THREAD

**Issue by lynnlee0522** [zmkfirmware/zmk#2728]
1. When I compile using the latest code (commit ID: bb486619a183f6df7fbb4620c80164555a22da0b, date: 19/12), it compiles successfully.
2. On this basis, I want to add trackpad functionality using the SPI protocol. When I compile, the following error occurs:
/Users/linli/zmk/zmk/app/src/pointing/input_listener.c:399: undefined reference to `__device_dts_ord_18'
3. I have already added config SPI with default y in Kconfig.defconfig. But the error still occurs.
4. there is my code： https://github.com/lynnlee0522/Newton1

**Comment by petejohanson** [comment]
Can you post the full `zephyr/.config` file? I assume you're building locally since I don't see the errors in GHA.

Can you post the complete build log, not just the failure snippet?

**Comment by lynnlee0522** [comment]
1. Thank you for your help. I am indeed building locally. The strange thing is that if I use GitHub Actions to build, it succeeds.
2. This is my local build situation.![image](https://github.com/user-attachments/assets/ddb74963-554f-4648-8702-2f27e88e2122)

**Comment by lynnlee0522** [comment]
Oh, I just solved the problem. I needed to include external modules in the compile command and put all the commands on the same line. Thanks again!
