### ISSUE TITLE
&mo inside another &mo issue

### ISSUE THREAD

**Issue by simonwjackson** [zmkfirmware/zmk#289]
When a momentary layer `(&mo)` exists inside another momentary layer on the same split, the opposite split gets stuck in that layer until both sides are reset.

This is my keymap for reference https://github.com/simonwjackson/zmk-config/blob/406e252b7440bcef113c8793a82a8b5b5a4cadc6/config/corne.keymap

**Comment by pluskid** [comment]
I'm having similar issue with a non-split keyboard. My layer config is like this:

```
base layer:  &mo 1  &mo 2
lower layer: &trans &mo 3
raise layer: &mo 3  &trans
layer 3:     &trans &trans
```

After I press both key to travel to layer 3, the whole keyboard is stuck in the `lower` layer.

**Comment by okke-formsma** [comment]
```
base    <&mo 1>
layer 1 <&kp A>
```
this is the smallest keymap to reproduce this issue. The layer state for position 0 was accidentally updated to include layer 1, even though layer 1 can not be active.
