### ISSUE TITLE
feat: Develop keymap migration script for standardized keys

### ISSUE THREAD

**Issue by innovaker** [zmkfirmware/zmk#299]
One of the consequences of #21 is that existing keymaps - both user and default - will subsequently contain deprecated key names.  Although we're planning to gradually phase them out over time, it would be helpful if there was a script to do the grunt work for each developer/user.  The *initial* use case being: user runs script, checks the replacements, adjusts any cosmetics (as necessary), and tests it.  Updates to any contributed keymaps can then be PR-ed with relative confidence.

### Specification
- Must be multi-platform (i.e. on the web or a multi-platform script).
- Must replace deprecated key names in a keymap.
- Must not replace or damage anything else!

### Substitutions
This is a list of the current default replacements.  The list's specifics may be updated as #21 goes through its final review cycles, but the general form should stay the same.
```js
[
  { from: "NUM_1", to: "N1" },
  { from: "NUM_2", to: "N2" },
  { from: "NUM_3", to: "N3" },
  { from: "NUM_4", to: "N4" },
  { from: "NUM_5", to: "N5" },
  { from: "NUM_6", to: "N6" },
  { from: "NUM_7", to: "N7" },
  { from: "NUM_8", to: "N8" },
  { from: "NUM_9", to: "N9" },
  { from: "NUM_0", to: "N0" },
  { from: "BKSP", to: "BSPC" },
  { from: "SPC", to: "SPACE" },
  { from: "EQL", to: "EQUAL" },
  { from: "TILD", to: "TILDE" },
  { from: "SCLN", to: "SEMI" },
  { from: "QUOT", to: "SQT" },
  { from: "GRAV", to: "GRAVE" },
  { from: "CMMA", to: "COMMA" },
  { from: "PRSC", to: "PSCRN" },
  { from: "SCLK", to: "SLCK" },
  { from: "PAUS", to: "PAUSE_BREAK" },
  { from: "PGUP", to: "PG_UP" },
  { from: "PGDN", to: "PG_DN" },
  { from: "RARW", to: "RIGHT" },
  { from: "LARW", to: "LEFT" },
  { from: "DARW", to: "DOWN" },
  { from: "UARW", to: "UP" },
  { from: "KDIV", to: "KP_DIVIDE" },
  { from: "KMLT", to: "KP_MULTIPLY" },
  { from: "KMIN", to: "KP_MINUS" },
  { from: "KPLS", to: "KP_PLUS" },
  { from: "UNDO", to: "K_UNDO" },
  { from: "CUT", to: "K_CUT" },
  { from: "COPY", to: "K_COPY" },
  { from: "PSTE", to: "K_PASTE" },
  { from: "VOLU", to: "K_VOL_UP" },
  { from: "VOLD", to: "K_VOL_DN" },
  { from: "CURU", to: null },
  { from: "LPRN", to: "LPAR" },
  { from: "RPRN", to: "RPAR" },
  { from: "LCUR", to: "LBRC" },
  { from: "RCUR", to: "RBRC" },
  { from: "CRRT", to: "CARET" },
  { from: "PRCT", to: "PRCNT" },
  { from: "LABT", to: "LT" },
  { from: "RABT", to: "GT" },
  { from: "COLN", to: "COLON" },
  { from: "KSPC", to: null },
  { from: "ATSN", to: "AT" },
  { from: "BANG", to: "EXCL" },
  { from: "LCTL", to: "LCTRL" },
  { from: "LSFT", to: "LSHFT" },
  { from: "RCTL", to: "RCTRL" },
  { from: "RSFT", to: "RSHFT" },
  { from: "M_NEXT", to: "C_NEXT" },
  { from: "M_PREV", to: "C_PREV" },
  { from: "M_STOP", to: "C_STOP" },
  { from: "M_EJCT", to: "C_EJECT" },
  { from: "M_PLAY", to: "C_PP" },
  { from: "M_MUTE", to: "C_MUTE" },
  { from: "M_VOLU", to: "C_VOL_UP" },
  { from: "M_VOLD", to: "C_VOL_DN" },
  { from: "GUI", to: "K_CMENU" },
];
```

**Comment by innovaker** [comment]
We're currently looking for someone(s) to pick up this task.

If you'd like to kick it off, please leave a comment so that we can open a dialogue and assign it to you.  Thanks!

**Comment by CrossR** [comment]
I can do this if nobody else will (and assuming there isn't a dev who only knows Python who wants to contribute to ZMK).

**Comment by innovaker** [comment]
Thanks @CrossR!  Nobody else has come forward (so far?).  Please let me know if you start it so that I can assign the issue to you.

**Comment by BrainWart** [comment]
~~Looks like the new keycodes are live, @ CrossR. I am of the same mind as you with this issue. It would have been a good opportunity for a Python developer to contribute if they wanted. If you're busy or don't need the load at the time, I think I can handle this as well.~~


There was some discussion about what would be the easiest for all ZMK users as well.
https://discord.com/channels/719497620560543766/719544230497878116/773410057052356618

Seems like a JavaScript app on the website may be most accessible to users who may not have any of the platform tools installed.

**Comment by innovaker** [comment]
I only specified Python as it's the most common cross-platform language.  But I'm happy for it to be done in Javascript if there's a path forward there.  Some users don't publish their GitHub repositories so I'd request that it can also be used from node also.

**Comment by innovaker** [comment]
I've updated the specification accordingly.

**Comment by innovaker** [comment]
I've also updated the mappings.

**Comment by innovaker** [comment]
Updated the mappings for `GUI` deprecation.

**Comment by innovaker** [comment]
Has anyone started work on this issue please?  The firmware improvements and associated documentation is now in `main`.

**Comment by joelspadin** [comment]
I have something that appears to be working on the few keymaps I've tested so far. Will put up something for more testing soon.
