### ISSUE TITLE
RGB strips flickering 

### ISSUE THREAD

**Issue by tominabox1** [zmkfirmware/zmk#305]
It appears there have been several reports of RGB strips and LEDs flickering in the current configurations. I am using the following strip and experienced this issue on my QAZ

`https://www.aliexpress.com/item/4000169932545.html`

I've tried another led strip (don't recall the source) and also had the same results. Tried different numbers of LEDs, behavior was the same.

Steps to reproduce: enable leds in your board.config. LEDs flicker in static and animated modes.

**Comment by Nicell** [comment]
Further testing was done today and the following items were noted:

- Confirmed genuine WS2812Bs with black tops work
- On genuine WS2812Bs, 2MHz-7.6MHz SPI frequency works properly.
- On unconfirmed WS2812 (possibly SK6812) with white tops, 4MHz-7.6MHz frequency works, but they flicker. Outside of that frequency issues arise.
- Shifting the one frame slightly doesn't result in any fixes
- Alternative firmware BlueMicro handles the same hardware fine using the Neopixel library

Based off of this, it seems as though the driver isn't working properly for certain LEDs. It's suspected this is SK6812s, but this isn't confirmed. Further testing and inspection of the signal of BlueMicro vs. ZMK using an oscilloscope may help pinpoint the issue.
