### ISSUE TITLE
Documentation: reduced width view of documentation hides the outline with no way to restore

### ISSUE THREAD

**Issue by leejunseok** [zmkfirmware/zmk#347]
If you open the documentation page (https://zmkfirmware.dev/docs) and reduce the width of your browser to the point where the outline on the left is auto-hidden, there's no way to restore the outline. 

Opening the hamburger menu shows only three options: "Docs", "Blog", and "Github" (the three links that are shown in the top bar when the docs are in full-width display mode.

Full width
<img width="673" alt="Screen Shot 2020-11-08 at 11 46 31 AM" src="https://user-images.githubusercontent.com/1222374/98482727-301f7880-21b8-11eb-890c-2387581577e1.png">

Reduced width, hamburger menu closed
<img width="720" alt="Screen Shot 2020-11-08 at 11 49 16 AM" src="https://user-images.githubusercontent.com/1222374/98482776-7b398b80-21b8-11eb-923e-6816af8e78e7.png">

Reduced width, hamburger menu open
<img width="803" alt="Screen Shot 2020-11-08 at 11 46 43 AM" src="https://user-images.githubusercontent.com/1222374/98482730-331a6900-21b8-11eb-8efb-7b43d7f80fae.png">

**Comment by innovaker** [comment]
Thanks for letting us know.  That's *probably* a bug in Docusaurus or perhaps a setting.

**Comment by Nicell** [comment]
This isn't a bug, just bad UX from Docusaurus IMO!

See here: 
![image](https://user-images.githubusercontent.com/9439650/98484128-eee89200-21d2-11eb-8b2e-e1ff4a85b347.png)

![image](https://user-images.githubusercontent.com/9439650/98484134-f7d96380-21d2-11eb-8910-4522b3aefbbd.png)

They move the menu location with very little visual indication.

**Comment by innovaker** [comment]
Ha, you're right, and I didn't even spot it.  Thanks @Nicell.

To be fair, we're using Docusaurus v2 which is **alpha**.

Sorry @leejunseok.  I'd suggest you speak to the Docusaurus team about it.
