### ISSUE TITLE
Community Funded USB VID

### ISSUE THREAD

**Issue by innovaker** [zmkfirmware/zmk#38]
From: https://discord.com/channels/719497620560543766/719565084208398406/722950144177209395

**Comment by jpconstantineau** [comment]
Perhaps consider getting one here: https://github.com/openmoko/openmoko-usb-oui

**Comment by petejohanson** [comment]
@jpconstantineau Nice! I hadn't seen this project. I will check it out.

**Comment by petejohanson** [comment]
Request submitted there: https://github.com/openmoko/openmoko-usb-oui/pull/15

**Comment by peterjc** [comment]
```
Vendor ID | Product ID | Description
...
0x1d50 | 0x615e | [https://zmkfirmware.dev ZMK Firmware]
```

Nice 🚀
