### ISSUE TITLE
Battery level doesn't update on Windows

### ISSUE THREAD

**Issue by bcat** [zmkfirmware/zmk#392]
My Crkbd showed battery level 98% when initially connected to my Windows desktop, and continues to do the same a day later. My Chrome OS workstation, though, shows battery level 87% and seemingly counting down correctly.

**Comment by bcat** [comment]
For comparison, BlueMicro did show a continuously updating battery level on Windows, though the range was weird (fully charged around 50% and dead around 15%).

**Comment by Wofiel** [comment]
This definitely occurs for me, but not 100% of the time, so I'm not sure what triggers it. My first guess is that it seems to be determined at pairing time?

Just now, after the battery level being stuck at 40% for about a week the last time I paired, I re-paired one of my Windows devices (Remove device, BT_CLR, re-add) and it's now correctly updating and matching my iOS device.

**Comment by joelspadin** [comment]
Mine only seems to update every time it reconnects from deep sleep.

**Comment by mattyams** [comment]
I too am having this problem except that after re-pairing to my devices updates to the battery level do not happen. I turned on logging and have attached the log here to reference. 

[https://pastebin.com/i57G0z3z](url)

**Comment by Brausmith** [comment]
Same issue for me with a Sofle RGB + Nice!Nano. I am on Windows 11 dev build.
Stuck on 62% which is what it was when first paired.

**Comment by hyx0329** [comment]
I encounter a similar issue on my Linux setup. After re-pairing the keyboard with my computer, the problem seems solved.

**Comment by joelspadin** [comment]
```
CONFIG_BT_GATT_ENFORCE_SUBSCRIPTION=n
```
in a .conf file provides a way to fix this now.
