### ISSUE TITLE
nullbits.co tidbit bring up

### ISSUE THREAD

**Issue by mcrosson** [zmkfirmware/zmk#425]
Place holder ticket for PR #424 that enables zmk on the nice!nano for the nullbits.co tidbit. I don't have a nice!nano yet and wanted to ensure a place holder was present in case other wanted to test the code and/or use it for their own tidbit builds.

**Comment by innovaker** [comment]
@mcrosson, can this be closed now?

**Comment by mcrosson** [comment]
Yes, with the PR merged this can be closed. Doing that now.
