### ISSUE TITLE
Raspbian/cmake versioning 

### ISSUE THREAD

**Issue by keyboard-magpie** [zmkfirmware/zmk#444]
When setting up build environment on raspbian, the latest cmake that is available through apt is 3.13, ZMK wants 3.15. 

Workaround for now is to compile 3.15 from source.

**Comment by keyboard-magpie** [comment]
Alternative workaround (easier, thanks @innovaker ) is to use buster-backports

**Comment by Nick-Munnich** [comment]
I'm going to close this as:
1. Although we currently require 3.20 for tests, general cmake is currently only marked as requiring 3.13.
2. It's been a number of years, and I'd be surprised if this still applies.
3. Realistically, even if it did still apply, I don't think anything would be done about it.
4. There are valid workarounds.
