### ISSUE TITLE
Feature Request: Double reset/bootloader for split keyboards

### ISSUE THREAD

**Issue by jmding8** [zmkfirmware/zmk#490]
Currently for split keyboards using Bluetooth for inter-half communications, &reset only triggers the central device to reset, while the peripheral device does not. This causes the two halves to disconnect, requiring the user to do a hardware reset on the peripheral device to re-connect the halves. Similarly, &bootloader causes only the central device to enter bootloader mode, requiring the user to trigger bootloader mode on the peripheral device via a reset-pin double-tap. It would be nice if there were &reset_peripheral, &bootloader_peripheral, &reset_all and &bootloader_all behaviors available

**Comment by Eyenseo** [comment]
Desperately needed - It would also be nice if `reset` is applied on each half - or take an index to say on which piece of a multi-piece keyboard.

**Comment by petejohanson** [comment]
> Desperately needed - It would also be nice if `reset` is applied on each half - or take an index to say on which piece of a multi-piece keyboard.

Check out #547 which will be fixing this.

**Comment by caksoylar** [comment]
Closing since #547 is merged.
