### ISSUE TITLE
Configuring rolling mod/layer taps

### ISSUE THREAD

**Issue by jmding8** [zmkfirmware/zmk#513]
The documentation seems to imply that, by default, mod/layer taps are configured as "hold-preferred", and that "Decision is made on other key-down." However, from testing my experience has been that if I execute a "rolling layer tap" within the tapping term, I end up getting a tap output from the layer-tap key.

This is what I'm doing:
1. LT(num, tab) down + timer start
2. j down
3. LT(num, tab) up
4. j up
5. 200 ms (tapping term) elapsed from timer start

The output is:
"	j"

I expect the output to be:
"4"

IMO, hold-preferred is likely primarily used for combinations like LT(num_layer, esc), where the tap behavior is somewhat less common than the layer/mod behavior, and where the user is expecting behavior similar to the shift key on regular keyboards. Thus, rolling inputs in time < tapping term should behave as the shift key does, i.e. the keydown event of the second key should coalesce the LT behavior into a hold behavior.

**Comment by okke-formsma** [comment]
@jmding8, can you share your keymap? I would expect this behavior to function as you describe.

**Comment by jmding8** [comment]
You are right, thank you for mentioning that you expected the described behavior, it prompted me to look into the layer-tap behavior and realizing that it is configured as tap-preferred (whereas I had assumed it was hold-preferred).

**Comment by okke-formsma** [comment]
I'm going to close this ticket. I agree we could improve the docs on holdtaps and layer taps, PRs are welcome.
