### ISSUE TITLE
Boot protocol not enabled

### ISSUE THREAD

**Issue by xudongzheng** [zmkfirmware/zmk#632]
Boot protocol may be necessary to use as USB keyboard with certain BIOS. Consider adding `CONFIG_USB_HID_BOOT_PROTOCOL=y`.

**Comment by xudongzheng** [comment]
Typically when sending HID data, the first byte is the report ID. That may need to be excluded when sending a boot report. It's also possible that boot reports are sent in a completely different manner.

**Comment by typorian** [comment]
Just to clear up what this question is about, I hadded the config switch you mentioned to my config but I still can't use my kyria with nice!nano v2 to enter the bitlocker pin. Is this expected behavior waiting for a fix or am I doing it wrong? Thank you!

**Comment by xudongzheng** [comment]
> Just to clear up what this question is about, I hadded the config switch you mentioned to my config but I still can't use my kyria with nice!nano v2 to enter the bitlocker pin. Is this expected behavior waiting for a fix or am I doing it wrong? Thank you!

No, that configuration is just step one of many steps needed to implement boot protocol. There is https://github.com/zmkfirmware/zmk/pull/1140 but that's unfortunately a bit outdated.

**Comment by xudongzheng** [comment]
Closing in favor of #913.
