### ISSUE TITLE
Docs contain keymaps with non-existent and deprecated key defines.

### ISSUE THREAD

**Issue by Nicell** [zmkfirmware/zmk#646]
Currently our example keymaps on the docs contain key defines that are deprecated or don't even exist. All keymaps in our docs should be run through the keymap upgrader. 

Example: `QUOTE` in https://zmkfirmware.dev/docs/features/keymaps#layers-1

**Comment by mcrosson** [comment]
I'm told the keymap updater can solve some of the pain of updating the codes on the page
