### ISSUE TITLE
Bug: sticky key quick-release releases too quickly

### ISSUE THREAD

**Issue by okke-formsma** [zmkfirmware/zmk#696]
My &sk LSFT key configured with `quick-release` doesn't do anything if I try to use the sticky behavior.  Pressing it triggers shift, but on key release the sticky behavior is stopped immediately.

**Comment by azor738** [comment]
Can replicate. Closer inspection shows Shift being released right before the other key (~7 ms, think it's a limitation of the logging I'm using), no matter the value of release-after-ms

**Comment by okke-formsma** [comment]
Should be fixed in that PR, @azor738 could you verify?

**Comment by azor738** [comment]
Yes, but away from the keyboard until Sunday. Will check then! Thanks,

**Comment by Hajime-Suzuki** [comment]
I also had this issue. For example, when I typed "test" quickly with `&sk LSHFT` without `quick-release`  I got "TEst" and "test" with it.  Now with this change, I get "Test" as expected at least with my nice!nano. 👍
