### ISSUE TITLE
CMD & Shift Mod-Taps cause weird behaviors in correlation with combos. 

### ISSUE THREAD

**Issue by ItsWaffIe** [zmkfirmware/zmk#713]
Board: Nice!Nano 
Shield: CRKBD 
User Repo: https://github.com/ItsWaffIe/zmk-config

### Shift Issues 
Using shifted mod taps with keys used in combos cause the combo key to be spammed and if the combo key is shifted, caps lock becomes enabled but can't be turned off. This is fixed by resetting each half. In the video below, it was Shift + Y which is a combo on TY which outputs " : ". 
[Example](https://drive.google.com/file/d/1Bp2mjAnFgjrcowRFCDgsrGfYBWBh5G5e/view?usp=sharing)

### CMD/Control Issues
I've tried multiple keycodes and all have resulted in this issue. The CMD keycode seems to get combined with whatever key I press next. In the video below, it was CMD + T.
[Example](https://drive.google.com/file/d/1COgOIdNgKQHF-hGqgLLKZjq1djwUCoph/view?usp=sharing)

**Comment by okke-formsma** [comment]
![image](https://user-images.githubusercontent.com/486179/109710017-72bcf480-7b9d-11eb-8d3f-66da90180ce4.png)

your videos are still on private mode?

I don't really understand what you're exactly doing. Can you tell me what sequence of keys you press, and how they're configured?

e.g.
* press `&kp A`
* press combo on positions 1 and 2, which are mapped to `&kp X` and `&kp Y`
* release `&kp A`
* etc

**Comment by ItsWaffIe** [comment]
> your videos are still on private mode?
Oops, fixed that 

> I don't really understand what you're exactly doing. Can you tell me what sequence of keys you press, and how they're configured?
Shift example: I have `&mt LSHFT A` and a combo that output `&kp COLON` when `&kp T` and `&kp Y` are pressed. If I hold `&mt LSHFT A` to get shift and press `&kp T` or `&kp Y`, it spams `&kp COLON` until I type other characters which are also now shifted and the only way to fix that is by resetting the controller. 

Command example: I have `&mt RCMD FSLH` and if I were to press any other key, like `&kp S` for example, Command & S remain held until the controller is reset.

**Comment by okke-formsma** [comment]
I think this will be fixed by https://github.com/zmkfirmware/zmk/pull/697. Can you set your west.yml to point to my branch and flash that firmware to test?

**Comment by ItsWaffIe** [comment]
Yep, seems to work nicely now. Thank you for your work.
