### ISSUE TITLE
Encoder docs inconsistent 

### ISSUE THREAD

**Issue by tominabox1** [zmkfirmware/zmk#717]
New keyboard shield 
![image](https://user-images.githubusercontent.com/14228518/109893480-5bd7da00-7c51-11eb-8794-90a9b91ecbb0.png)
Encoders
![image](https://user-images.githubusercontent.com/14228518/109893498-61cdbb00-7c51-11eb-8e4e-5ec536281590.png)

As you can see, the order of EC11_CONFIG vs CONFIG_EC11

**Comment by caksoylar** [comment]
It looks like this was fixed at some point: ![image](https://user-images.githubusercontent.com/7876996/152046181-e4ef68b7-57d7-4e9a-b7b9-1e319044204d.jpeg)
