### ISSUE TITLE
Support modifiers for C_VOL_UP and C_VOL_DN

### ISSUE THREAD

**Issue by jamesramsay** [zmkfirmware/zmk#741]
When using MacOS, using Shift+Option+Volume Up/Down increases the volume by a 1/4 increments. This works with ZMK when they are separate keys chorded together.

However, it doesn't seem possible to combine into a single keypress with either:

```
&kp LS(LA(C_VOL_UP))
```

Or when using an encoder:

```
sensor-bindings = <&inc_dec_kp LS(LA(C_VOL_UP)) LS(LA(C_VOL_DN))>;
```

Are modifiers not supported for certain groups of key code?

**Comment by okke-formsma** [comment]
It's supported for consumer keycodes, but not for sensor bindings.

**Comment by jamesramsay** [comment]
@okke-formsma C_VOL_UP works just fine without modifiers. It also works fine when I hold modifier keys myself and turn the encoder.

It doesn't work when I apply the modifiers in the keymap `LS(LA(C_VOL_UP))`

**Comment by caksoylar** [comment]
Would #1038 affect this behavior? It would be good to test with a fresh build.

**Comment by petejohanson** [comment]
Yeah, re-testing would be good, I believe this is fixed by that PR.

**Comment by caksoylar** [comment]
I tested with `LS(C_VOL_UP)` on Windows, below is the results of tapping `LS(INS)` and then the shifted volume up, both of which show the same sequence of mod+key presses:
![image](https://user-images.githubusercontent.com/7876996/162036117-1390d1e5-702d-408a-96ba-497c3d0c265f.png)

I don't have a Mac to test the original keycode and see if it works, it would be good if someone can test and report.

**Comment by dxmh** [comment]
Can confirm `&kp LS(LA(C_VOL_UP))` increases the volume in 1/4 increments for me.

* Latest version of zmk `main` 
* macOS 12.3
* `CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y` (in case it has relevance)

**Comment by caksoylar** [comment]
Thanks @dxmh, sounds like this issue is fixed then.

**Comment by jamesramsay** [comment]
Thanks y'all 🙌
