### ISSUE TITLE
Docs Combo example does not compile

### ISSUE THREAD

**Issue by MvEerd** [zmkfirmware/zmk#755]
The example for combos in the documentation does not seem to compile;
https://github.com/MvEerd/zmk-config/commit/c4fb41e1ddab4874b30cc40f8c0552ebff7e5f0b

It errors on the `layers = <-1>;` line.
After removing this line or [changing the value to a non-negative integer](https://github.com/MvEerd/zmk-config/commit/dc19e606d863c491bc1dd8947b0e0df0b96d66e5) it compiles fine.
Any other array containing a negative integer seems to fail as well; `layers = <0 -1>;`

Is this a devicetree syntax bug or limitation?
I'm not able to find much more on this than the following;
> 'type: array' is for properties that are assigned zero or more 32-bit values

https://docs.zephyrproject.org/2.5.0/guides/dts/bindings.html

**Comment by okke-formsma** [comment]
Apparently the 'all layers' feature only works by not providing any value for the `layers` parameter, so it defaults to -1.

**Comment by MvEerd** [comment]
The -1 is indeed superfluous in this case. I just wondered where the syntax error came from before offering a PR for the docs to say so.
Is it a devicetree limitation? I don't see a configuration affecting this apart from the default being set

**Comment by okke-formsma** [comment]
https://docs.zephyrproject.org/latest/guides/dts/intro.html#syntax-and-structure 

> Devicetree nodes can also have properties. Properties are name/value pairs. Property values can be any sequence of bytes. In some cases, the values are an array of what are called cells. A cell is just a 32-bit unsigned integer.

**Comment by MvEerd** [comment]
Ah, so they are indeed unsigned, that explains it. Thanks for pointing that part of the docs out!

Was indeed confused that you could still configure it as `-1` default

**Comment by joelspadin** [comment]
> So it's actually kind of funky that the -1 default works :')

I'm pretty sure you're just getting `(uint32_t)(-1)` here, so the max possible uint32_t. Then since `combo_cfg::layers` is an array of signed integers, you get `(int8_t)(uint32_t)(4294967295)`, which fortunately happens to be -1.

**Comment by MvEerd** [comment]
Fixed by #757
