### ISSUE TITLE
Add LSHIFT and RSHIFT aliases

### ISSUE THREAD

**Issue by joelspadin** [zmkfirmware/zmk#783]
Using `LSHIFT` or `RSHIFT` instead of `LSHFT` or `RSHFT` seems to be a recurring error. We should probably add those aliases.

Examples:
* https://discord.com/channels/719497620560543766/719909884769992755/839919783758921788
* https://discord.com/channels/719497620560543766/719909884769992755/807859580327165952
* https://discord.com/channels/719497620560543766/719909884769992755/805518945620721685
* https://discord.com/channels/719497620560543766/719909884769992755/804897080836620338
* https://discord.com/channels/719497620560543766/719909884769992755/829092687725985792
* https://discord.com/channels/719497620560543766/813882537436905552/822175709711302716

**Comment by innovaker** [comment]
This also throws up the wonderful dilemma of whether we should replace the numerous instances of `LSHFT` and `RSHFT` throughout the documentation (and keymaps).
