### ISSUE TITLE
Sticky keys inconsistent behavior in secondary layers

### ISSUE THREAD

**Issue by arhl-gh** [zmkfirmware/zmk#815]
For example, LS(N1) gives 1 instead of ! around once every ten key presses. This behavior has been noted when the sticky key is in a secondary layer.  

Happens also for RA(code).

**Comment by joelspadin** [comment]
Might be the same issue as #759

**Comment by arhl-gh** [comment]
Thank you for your answer. It is a similar case indeed, the behavior seems the same although I'm using Fedora 34 instead of a remote connection.

**Comment by arhl-gh** [comment]
I have found that is issue is only present if I use Wayland in Fedora. I have switched to Xorg and the erratic comportment of the sticky keys is no longer present. Please let me know if some other info could be useful to you.

**Comment by caksoylar** [comment]
Closing, since this seems to be a related to the timing of keycodes with implicit modifiers similar to #759 and not related to sticky keys or non-default layers.
