### ISSUE TITLE
Symbol KP being sent as number in Windows RDP Session (Symbols recognized as Number keys)

### ISSUE THREAD

**Issue by halfurness** [zmkfirmware/zmk#850]
In a windows RDP session, clicking &kp EXCL sends by default the number 1, only when holding shift does the ! symbol get sent.
I have a QMK keyboard with the equivalent code on it that is this does not happen to.

**Comment by halfurness** [comment]
If the symbol keys are just shifted number keys then I guess this might be happening because of https://github.com/zmkfirmware/zmk/issues/759

**Comment by joelspadin** [comment]
Yeah. Many symbols are just shifted keys so I think this is the same as #759. Closing this as a duplicate.
