### ISSUE TITLE
[Feature Request]: Utilize Vial for Realtime Keymap Updating

### ISSUE THREAD

**Issue by luigi311** [zmkfirmware/zmk#852]
For QMK the default Realtime Keymap Updating tool is VIA, I am proposing utilizing Vial as the tool for remaping.

Vial has the benefit of being open source so if the developer ever abandons it, it can still be updated and maintained by a third party. They also have some security benefits to prevent the keys from being switched to something else without the users consent. Keyboards also do not have to be maintained on the Vial side of things as the json will live inside the firmware and retrieved dynamically so keyboard support just needs to be handled on a single repo.

More information is here
https://get.vial.today/
https://github.com/vial-kb

**Comment by lucastercas** [comment]
So, is there any tool that I can use to update the keymaps realtime? Without having to edit the `.keymap` file and reflashing?

**Comment by caksoylar** [comment]
There isn't one at the moment, no. There is no support on the ZMK backend for such an application yet.

**Comment by lublak** [comment]
Just my idea.
I currently use an iPad. One dream would be to create a keyboard that can change the keyboard Lay-out in real time over Bluetooth.
So a backend that support Bluetooth keymap remapping would be awesome. So after some time there can also be a iPad app to configure the keyboard. (Flutter would be a nice framework for this, it works on android, iPad, windows, Linux and Mac)

**Comment by myst729** [comment]
Given that ZMK supports UF2 firmware update, is it possible to just drag a keymap file (YAML, JSON or whatever, even plain TXT) under its DFU mode?

**Comment by Nick-Munnich** [comment]
Closing as ZMK is planned and will soon be using ZMK studio to attain the same effect.

**Comment by cmandlbaur** [comment]
Ok, but how soon is soon™️?

**Comment by Nick-Munnich** [comment]
> Ok, but how soon is soon™️?

Currently in alpha, can be tested. See the Discord for more details, also see https://main.alpha.zmk.studio/ and #2268
