### ISSUE TITLE
Include the Nullbits Nibble 65% as supported hardware in the docs

### ISSUE THREAD

**Issue by jasonj2232** [zmkfirmware/zmk#854]
The [Nullbits Nibble 65%](https://nullbits.co/nibble/) is supported by ZMK but the docs haven't been updated to reflect that fact. Hence, update the 'keyboard shields' section in the 'supported hardware' page of the ZMK docs.

**Comment by caksoylar** [comment]
Nibble is now included on the supported hardware page (I am guessing since the metadata changes?), so closing.
