### ISSUE TITLE
User config shields fail to apply a keyboard name to BLE

### ISSUE THREAD

**Issue by Nicell** [zmkfirmware/zmk#88]
With my nice!60 shield definition in my user config, the BLE name doesn't get applied and just shows a MAC address on devices. (https://github.com/Nicell/zmk-config/tree/master/config/boards/shields/nice60)

USB oddly seems to still have the proper name.

**Comment by petejohanson** [comment]
@Nicell can you capture your final `.config` from your build in your action, so we can see what's set at that level? TIA.

**Comment by Nicell** [comment]
@petejohanson I've got the .config as another artifact now: https://github.com/Nicell/zmk-config/actions/runs/211180850

**Comment by Nicell** [comment]
Taking a closer look, not even `SHIELD_NICE60` is getting defined in the .config. This means that the `def_bool` for `shields_list_contains` is failing in user configs.
