### ISSUE TITLE
Basic setup for Raspberry OS is incorrect

### ISSUE THREAD

**Issue by TheWeirdDodo** [zmkfirmware/zmk#880]
Hi, I have recently tried to install ZMK on a rpi and I've ran into an issue where I wasn't able to build any firmware. After following the [guide](https://zmk.dev/docs/development/setup) a few times and then checking it, it seems to be a typo when installing the toolchain.

One of the exports which needs to be added to `~/.zephyrrc` :

`export CROSS_COMPILE=/usr/bin/arm-none-eabi-`

seems to be missing the appendix `gcc`.

If someone can double check on this I guess it would save some troubleshooting for people building on a raspberry.

**Comment by caksoylar** [comment]
This was overhauled in #1621, if the new instructions don't work please re-open.
