### ISSUE TITLE
Sticky shift produces multiple uppercase letters

### ISSUE THREAD

**Issue by dxmh** [zmkfirmware/zmk#903]
I use `&sk LSHFT` on a thumb key as my primary method of typing an uppercase letter, so that holding down keys is not necessary (this behaviour is called “one-shot shift” in QMK). 

However, this almost always results in two uppercase letters for me. 

For example:

> HEllo world. THis is an example for the GItHUb issue. 

This feels like it might be exacerbated by a “rolling” typing style, e.g. typing fast and possibly rolling some of the `&sk LSHFT` `&kp H` `&kp E` keys in the `HEllo world` example above. 

I think this may be related to #829.

**Comment by trankillity** [comment]
I am also experiencing this. Initially I thought it might have been lazy typing is definitely more related to ZMK. I believe that the sticky keys code is occasionally applying the stickied key on key UP rather than just on key DOWN. This would explain why this is happening.

You can reproduce this in a simple fashion by holding a `&sk LSHIFT` bind for a second, not pressing anything, then pressing a key before the `release-after-ms` period. It still produces the capital letter, when it should really only produce it on key down, not key up.

Use cases where this causes significant issues are when using modifiers and the mouse (shift clicking, etc).

**Comment by dxmh** [comment]
> I believe that the sticky keys code is occasionally applying the stickied key on key UP rather than just on key DOWN.

Interesting observation. It could be worth trying the `quick-release` config option which is enabled by default for sticky _layer_ keys:

> Sticky layers behave slightly different from sticky keys. They are configured to `quick-release`. This means that the layer is released immediately when another key is pressed. "Normal" sticky keys are not `quick-release`; they are released when the next key is released. This makes it possible to combine sticky layers and sticky keys as such: tap `&sl 1`, tap `&sk LSHIFT` on layer 1, tap `&kp A` on base layer to output shift+A.

https://zmk.dev/docs/behaviors/sticky-layer/#advanced-usage

**Comment by trankillity** [comment]
> Interesting observation. It could be worth trying the `quick-release` config option which is enabled by default for sticky _layer_ keys:

Very interesting! How would I go about adding that in? No docs about it at all unfortunately. Is it as simple as the `hold-tap` configuration of `flavor`?

**Comment by trankillity** [comment]
Have just found the new docs generated in [this PR](https://github.com/zmkfirmware/zmk/pull/722) which link to [these docs](https://deploy-preview-722--zmk.netlify.app/docs/config/behaviors/#sticky-key).

In the aforementioned docs, it describes the function of the `quick-release` behaviour of sticky keys as...

> Release the sticky key on the next key press instead of **_release_**

This default behaviour would 100% be causing this rolled issue as sticky keys is also triggering when letting go of the key.
```&sk LSHIFT down
&kp A down
&kp A up
&sk LSHIFT up
&kp R down
&kp R up
&kp T down
&kp T up```
Above would currently produce `ARt`, when you would expect `Art`.

So the default behaviour should be on key press, not key release. This is also the default mechanism of QMK one-shots. By changing to that behaviour, the above example would properly produce `Art`.

**Comment by dxmh** [comment]
I've now typed for a good few hours with `quick-release` enabled and I've not had a single occurrence of the multiple uppercase letters described in the [opening comment](https://github.com/zmkfirmware/zmk/issues/903#issue-964125639). :partying_face:

I've currently configured it in my `.keymap` file like so:

```diff
 &sk {
     release-after-ms = <2000>;
+    quick-release;
 };
 
 / {
     keymap {
         ...
     };
 };
```

This configuration applies `quick-release` to _all_ sticky keys, which has some drawbacks (e.g. the ability to chain sticky modifiers is lost), but it could be easily tweaked to apply only to a dedicated shift key if desired.

**Comment by dxmh** [comment]
The issue (sticky shift producing multiple uppercase letters) is completely non-existent with`quick-release` enabled as per https://github.com/zmkfirmware/zmk/issues/903#issuecomment-909209198. 👌

**Comment by yangit** [comment]
Sorry, why is "quick release" makes it impossible to chain sticky modifiers?
Should not quick release only release on non modifier keys?
I.e. if I:
```
tap &sk LSHIFT 
tap &sk LALT 
press A 
press B
release A
release B
```
I expect OS to see:
```
ALT+Shift+A
B
```
Is there a way to implement such a behavior?

**Comment by trankillity** [comment]
The question is not related to the issue at all.

But to answer, simply don't use `quick-release`. It's entire purpose is to PREVENT chaining of mods unless held.
