### ISSUE TITLE
ZMK Lacks USB HID Boot Protocol (Needed For FileVault or BIOS)

### ISSUE THREAD

**Issue by xudongzheng** [zmkfirmware/zmk#913]
If FileVault (full disk encryption) is turned on in macOS, ZMK over USB currently cannot be used on the boot login screen before the disk is decrypted. This is because ZMK does not implement the boot HID protocol for USB and FileVault does not use the report protocol.

**Comment by rstacruz** [comment]
I can confirm that my ZMK keyboard doesn't work on the FileVault screen either (Microdox, nice!nano v2, zmk 2.5). However, QMK keyboards work just fine.

**Comment by rbitanga** [comment]
I have this working with Monterey but don't have older versions to test with. It will most likely at the very least work for all Macs released within the past decade since the HID spec hasn't been updated since 2001 and the official spec appears to be exported from MS Word 2000.

**Comment by xudongzheng** [comment]
It seems that the FileVault login on my M1 MacBook running macOS 13 supports both Bluetooth keyboards and USB HID report protocol (could be new for M1 Macs, could be new in macOS 13, not sure).

**Comment by amadeus** [comment]
Definitely noticed this issue on my two macs -- an Intel iMac and Macbook Pro M1, both with macOS 13 (Ventura). At the very least it would be great if they could work over USB. My QMK keyboards have no problem with this.

**Comment by xudongzheng** [comment]
This is closed by #1793.
