### ISSUE TITLE
Tidbit missing semicolon

### ISSUE THREAD

**Issue by kevinmgee** [zmkfirmware/zmk#928]
Default build script fails when using board Nice!Nano v2 and Tidbit shield.

https://github.com/zmkfirmware/zmk/blob/e491c282e74559d10818394feae3d64c7a559acf/docs/static/setup.sh#L121
[logs_1.zip](https://github.com/zmkfirmware/zmk/files/7102986/logs_1.zip)

Missing semicolon after split = "n"
(Same issue with missing semicolon on next line)

Build fails because Tidbit is not a split keyboard shield.

**Comment by dxmh** [comment]
@kevinmgee This has now been fixed in https://github.com/zmkfirmware/zmk/pull/931.
