### ISSUE TITLE
Setup script fails due to `sed` error

### ISSUE THREAD

**Issue by dxmh** [zmkfirmware/zmk#949]
A Discord user reported the following error when running the setup script (on Manjaro) for Sweep:

```
sed: -e expression #3, char 25: unknown option to `s'
```

I’m currently away from a computer so I haven’t had the chance to check it out properly, but likely some escaping is needed to handle the slash in the `Cradio/Sweep` shield name.

https://github.com/zmkfirmware/zmk/blob/a7908a94de851b8e9cec41ec11ecc0fe2cef2d47/app/boards/shields/cradio/cradio.zmk.yml#L3
https://github.com/zmkfirmware/zmk/blob/b82bbb5ba22ef5c4346e82ccd41d3f794a4bf376/docs/src/templates/setup.sh.mustache#L191

**Comment by MangoIV** [comment]
I think that even if escaping a directory `/` was possible that is not a sane way to do it. Imho it'd be the better option to just replace all `/`s with `-` or `_`
