### ISSUE TITLE
Feature request: Enable layer with modifiers active

### ISSUE THREAD

**Issue by dxmh** [zmkfirmware/zmk#968]
This is often requested on Discord by new users. 

Similar to how pressing `&mo NUMBER` currently enables a number layer, this new behaviour would allow for pressing something like `&mom LSHIFT NUMBER` to activate shift _and_ enable the number layer — with this key pressed, pressing `&kp N1` (from the number layer) would output `!`. 

Additionally, I understand users also wish to use this key as a standalone modifier (for example, having the ability to hold the key and click the mouse for a shift-click).

**Comment by caksoylar** [comment]
This is now possible with macros merged in so I assume it can be closed, see [the example in the docs](https://zmk.dev/docs/behaviors/macros#layer--modifier) for an implementation.
