### ISSUE TITLE
Inform users in docs that TRRS cables are not supported/have limited support

### ISSUE THREAD

**Issue by HeeToTheHo** [zmkfirmware/zmk#981]
TRRS cables are known to cause issues when hotswapped while using ZMK firmware. Multiple reports of issues arising when attempting to use TRRS cables, especially on boards such as the Corne.

![image](https://user-images.githubusercontent.com/49014052/137607224-a35ac78d-e7d6-4d1b-86f4-6badcb92876b.png)

**Comment by caksoylar** [comment]
Closing this now, since the FAQ covers the wired split part: https://zmk.dev/docs/faq#does-zmk-support-wired-split. Like Joel noted, this would be better covered in the documentation for particular hardware.
