### ISSUE TITLE
Ble Passkey does not work properly

### ISSUE THREAD

**Issue by cyz0105** [zmkfirmware/zmk#991]
After I configure CONFIG_ZMK_BLE_PASSKEY_ENTRY, I flash the new firmware, clear the keyboard ble profile by using BLE_CLR, delete paired keyboard on my PC, reconnect the keyboard, But I pressed the keys in the number area on the keyboard, following the numbers displayed on the PC, and the keyboard didn't respond, The pairing times out after 15 seconds . Is this a bug or a feature that is not fully implemented, or am I not configured properly? If yes, please advise how to modify the configuration. Thanks (Machine translation may not be accurate)

DEBUG message:
<dbg> zmk.connected: Connected thread: 0x20002c10
<dbg> zmk.connected: Connected 08:5b:d6:cf:7c:17 (public)
<dbg> zmk.update_advertising: advertising from 0 to 2
<dbg> zmk.auth_pairing_accept: role 1, open? yes
<dbg> zmk.auth_passkey_entry: Passkey entry requested for 08:5b:d6:cf:7c:17 (public)
<dbg> zmk.le_param_updated: 08:5b:d6:cf:7c:17 (public): interval 12 latency 30 timeout 400
<err> bt_smp: SMP Timeout
<err> zmk: Security failed: 08:5b:d6:cf:7c:17 (public) level 1 err 8
<dbg> zmk.disconnected: Disconnected from 08:5b:d6:cf:7c:17 (public) (reason 0x13)
<dbg> zmk.update_advertising: advertising from 2 to 2

**Comment by caksoylar** [comment]
This functionality was restored after #1097 was merged, can you try again?

**Comment by cyz0105** [comment]
> This functionality was restored after #1097 was merged, can you try again?

Sorry it took so long to reply you. Yes, I have tested the pin authentication and it works very well! Thank you

**Comment by cyz0105** [comment]
I have tested the pin authentication and it works very well!

**Comment by petejohanson** [comment]
> I have tested the pin authentication and it works very well!

Thanks for testing! What host operating systems did you use it with?
